/**
 * Role-Based Access Control (RBAC) Configuration
 *
 * Defines roles and their permissions for the Employee Onboarding System.
 * This is a Node.js version matching the TypeScript definitions in the frontend.
 */

// Role Definitions
const ROLES = {
  ADMIN: 'ADMIN',
  HR: 'HR',
  IT: 'IT',
  MANAGER: 'MANAGER',
  FINANCE: 'FINANCE',
  SVP: 'SVP',
  EMPLOYEE: 'EMPLOYEE',
  VIEWER: 'VIEWER',
};

// Permission Definitions
const PERMISSIONS = {
  // Pre-hire Permissions
  PREHIRE_CREATE: 'PREHIRE_CREATE',
  PREHIRE_READ: 'PREHIRE_READ',
  PREHIRE_UPDATE: 'PREHIRE_UPDATE',
  PREHIRE_DELETE: 'PREHIRE_DELETE',

  // Package Permissions
  PACKAGE_CREATE_STANDARD: 'PACKAGE_CREATE_STANDARD',
  PACKAGE_CREATE_EXCEPTION: 'PACKAGE_CREATE_EXCEPTION',
  PACKAGE_READ: 'PACKAGE_READ',
  PACKAGE_UPDATE: 'PACKAGE_UPDATE',
  PACKAGE_DELETE: 'PACKAGE_DELETE',

  // Hardware Permissions
  HARDWARE_CREATE: 'HARDWARE_CREATE',
  HARDWARE_READ: 'HARDWARE_READ',
  HARDWARE_UPDATE: 'HARDWARE_UPDATE',
  HARDWARE_DELETE: 'HARDWARE_DELETE',

  // Software Permissions
  SOFTWARE_CREATE: 'SOFTWARE_CREATE',
  SOFTWARE_READ: 'SOFTWARE_READ',
  SOFTWARE_UPDATE: 'SOFTWARE_UPDATE',
  SOFTWARE_DELETE: 'SOFTWARE_DELETE',
  SOFTWARE_ASSIGN: 'SOFTWARE_ASSIGN',
  SOFTWARE_RECLAIM: 'SOFTWARE_RECLAIM',

  // Approval Permissions
  APPROVAL_CREATE: 'APPROVAL_CREATE',
  APPROVAL_READ: 'APPROVAL_READ',
  APPROVAL_UPDATE: 'APPROVAL_UPDATE',
  APPROVAL_DELETE: 'APPROVAL_DELETE',
  APPROVAL_APPROVE: 'APPROVAL_APPROVE',
  APPROVAL_REJECT: 'APPROVAL_REJECT',

  // Admin Permissions
  ADMIN_ROLE_MANAGE: 'ADMIN_ROLE_MANAGE',
  ADMIN_SETTINGS: 'ADMIN_SETTINGS',
};

// Role-Permission Mappings
const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS), // Full access

  [ROLES.HR]: [
    PERMISSIONS.PREHIRE_CREATE,
    PERMISSIONS.PREHIRE_READ,
    PERMISSIONS.PREHIRE_UPDATE,
    PERMISSIONS.PREHIRE_DELETE,
    PERMISSIONS.PACKAGE_CREATE_EXCEPTION, // Can create exception packages only
    PERMISSIONS.PACKAGE_READ,
    PERMISSIONS.HARDWARE_READ,
    PERMISSIONS.SOFTWARE_READ,
    PERMISSIONS.APPROVAL_CREATE,
    PERMISSIONS.APPROVAL_READ,
  ],

  [ROLES.IT]: [
    PERMISSIONS.PREHIRE_READ,
    PERMISSIONS.PACKAGE_CREATE_STANDARD,
    PERMISSIONS.PACKAGE_CREATE_EXCEPTION,
    PERMISSIONS.PACKAGE_READ,
    PERMISSIONS.PACKAGE_UPDATE,
    PERMISSIONS.HARDWARE_CREATE,
    PERMISSIONS.HARDWARE_READ,
    PERMISSIONS.HARDWARE_UPDATE,
    PERMISSIONS.HARDWARE_DELETE,
    PERMISSIONS.SOFTWARE_CREATE,
    PERMISSIONS.SOFTWARE_READ,
    PERMISSIONS.SOFTWARE_UPDATE,
    PERMISSIONS.SOFTWARE_DELETE,
    PERMISSIONS.SOFTWARE_ASSIGN,
    PERMISSIONS.SOFTWARE_RECLAIM,
    PERMISSIONS.APPROVAL_READ,
    PERMISSIONS.APPROVAL_UPDATE,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.PREHIRE_READ,
    PERMISSIONS.PACKAGE_READ,
    PERMISSIONS.HARDWARE_READ,
    PERMISSIONS.SOFTWARE_READ,
    PERMISSIONS.APPROVAL_CREATE,
    PERMISSIONS.APPROVAL_READ,
  ],

  [ROLES.FINANCE]: [
    PERMISSIONS.PREHIRE_READ,
    PERMISSIONS.PACKAGE_READ,
    PERMISSIONS.HARDWARE_READ,
    PERMISSIONS.SOFTWARE_READ,
    PERMISSIONS.APPROVAL_READ,
  ],

  [ROLES.SVP]: [
    PERMISSIONS.PREHIRE_READ,
    PERMISSIONS.PACKAGE_READ,
    PERMISSIONS.HARDWARE_READ,
    PERMISSIONS.SOFTWARE_READ,
    PERMISSIONS.APPROVAL_READ,
    PERMISSIONS.APPROVAL_APPROVE,
    PERMISSIONS.APPROVAL_REJECT,
  ],

  [ROLES.EMPLOYEE]: [
    PERMISSIONS.PREHIRE_READ,
    PERMISSIONS.PACKAGE_READ,
    PERMISSIONS.HARDWARE_READ,
    PERMISSIONS.SOFTWARE_READ,
  ],

  [ROLES.VIEWER]: [
    PERMISSIONS.PREHIRE_READ,
    PERMISSIONS.PACKAGE_READ,
    PERMISSIONS.HARDWARE_READ,
    PERMISSIONS.SOFTWARE_READ,
    PERMISSIONS.APPROVAL_READ,
  ],
};

/**
 * Get permissions for a role
 */
function getRolePermissions(roleName) {
  return ROLE_PERMISSIONS[roleName] || [];
}

/**
 * Check if a user has a specific permission
 */
function hasPermission(userRoles, permission) {
  if (!Array.isArray(userRoles) || userRoles.length === 0) {
    return false;
  }

  // Get all permissions for all user roles
  const allPermissions = userRoles.flatMap(role => getRolePermissions(role));

  return allPermissions.includes(permission);
}

/**
 * Get user roles based on Azure AD groups
 */
function getUserRolesFromGroups(groups, db) {
  // ADMIN role from Azure AD group
  const ADMIN_GROUP_ID = '1322ab5f-d86d-4c9e-b863-fba031615857';
  if (groups && groups.includes(ADMIN_GROUP_ID)) {
    return [ROLES.ADMIN];
  }

  // TODO: Fetch from database using user email
  // For now, default to EMPLOYEE role
  return [ROLES.EMPLOYEE];
}

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  getRolePermissions,
  hasPermission,
  getUserRolesFromGroups,
};
