// ============================================================================
// UXP PLATFORM - MOCK DATA
// ============================================================================
// Sample data for development and testing
// Includes: Campaigns, Events, Venues, People Assignments, QR Codes

import {
  Hardware,
  Software,
  LicensePool, // Phase 10: NEW
  Package,
  PackageVersion,
  PackageAssignment,
  PackageCostBreakdown,
  PreHire,
  Employee,
  ApprovalRequest,
  HelixTicket,
  OnboardingTask,
  OnboardingProgress,
  FreezePeriod,
  FreezePeriodNotification,
  Venue, // UXP: Venue management
  Campaign,
  Event,
  Venue,
  PeopleAssignment,
  QRCode,
  UserRole,
  UserRoleAssignment,
  CampaignStatistics,
  EventAnalytics,
} from '../types';

// ============================================================================
// CAMPAIGNS (10 realistic examples)
// ============================================================================

export const mockCampaigns: Campaign[] = [
  // AMEX Music Activation
  {
    id: 'camp-amex-music-001',
    campaignName: 'AMEX Unstaged Summer Tour 2025',
    campaignDescription: 'American Express Unstaged summer music festival activation series',
    campaignNotes: 'Partnership with Live Nation, 8-city tour',
    client: 'American Express',
    eventType: 'Music Festival',
    masterProgram: 'AMEX Unstaged',
    region: 'National',
    status: 'active',
    year: 2025,
    month: 6,
    yearMonth: '2025-06',
    campaignOwner: 'sarah.johnson@momentumww.com',
    campaignOwnerEmail: 'sarah.johnson@momentumww.com',
    createdBy: 'sarah.johnson@momentumww.com',
    createdByName: 'Sarah Johnson',
    createdOn: new Date('2025-01-15'),
    updatedBy: 'sarah.johnson@momentumww.com',
    updatedByName: 'Sarah Johnson',
    updatedOn: new Date('2025-03-10'),
    jobNumbers: ['AMEX-2025-001', 'JOB-12345'],
    visible: true,
  },

  // Verizon NFL Activation
  {
    id: 'camp-verizon-nfl-001',
    campaignName: 'Verizon NFL Sponsorship 2025',
    campaignDescription: '5G Stadium Experience - NFL season activation',
    campaignNotes: 'All home games for 4 key markets',
    client: 'Verizon',
    eventType: 'Sports Activation',
    masterProgram: 'NFL Sponsorship',
    region: 'National',
    status: 'active',
    year: 2025,
    month: 9,
    yearMonth: '2025-09',
    campaignOwner: 'michael.chen@momentumww.com',
    campaignOwnerEmail: 'michael.chen@momentumww.com',
    createdBy: 'michael.chen@momentumww.com',
    createdByName: 'Michael Chen',
    createdOn: new Date('2025-02-01'),
    jobNumbers: ['VZ-NFL-2025', 'JOB-23456'],
    visible: true,
  },

  // Coca-Cola Product Sampling
  {
    id: 'camp-cocacola-sampling-001',
    campaignName: 'Coca-Cola Zero Sugar Launch',
    campaignDescription: 'Product sampling and brand experience for new zero sugar formula',
    campaignNotes: 'Target Gen Z audiences in major metro areas',
    client: 'Coca-Cola',
    eventType: 'Product Sampling',
    masterProgram: 'Zero Sugar Launch',
    region: 'National',
    status: 'planning',
    year: 2025,
    month: 7,
    yearMonth: '2025-07',
    campaignOwner: 'emily.rodriguez@momentumww.com',
    campaignOwnerEmail: 'emily.rodriguez@momentumww.com',
    createdBy: 'emily.rodriguez@momentumww.com',
    createdByName: 'Emily Rodriguez',
    createdOn: new Date('2025-03-01'),
    jobNumbers: ['COKE-ZS-2025', 'JOB-34567'],
    visible: true,
  },

  // Constellation Brands (Corona)
  {
    id: 'camp-corona-beach-001',
    campaignName: 'Corona Beach Tour 2025',
    campaignDescription: 'Corona Extra beach activation series',
    campaignNotes: '10 coastal cities, summer weekends',
    client: 'Constellation Brands',
    eventType: 'Brand Experience',
    masterProgram: 'Corona Beach Program',
    region: 'West Coast',
    status: 'active',
    year: 2025,
    month: 5,
    yearMonth: '2025-05',
    campaignOwner: 'david.kim@momentumww.com',
    campaignOwnerEmail: 'david.kim@momentumww.com',
    createdBy: 'david.kim@momentumww.com',
    createdByName: 'David Kim',
    createdOn: new Date('2025-02-15'),
    updatedBy: 'david.kim@momentumww.com',
    updatedByName: 'David Kim',
    updatedOn: new Date('2025-04-01'),
    jobNumbers: ['CORONA-BEACH-2025'],
    visible: true,
  },

  // AMEX Business Activation
  {
    id: 'camp-amex-biz-001',
    campaignName: 'AMEX Small Business Saturday 2025',
    campaignDescription: 'National small business support campaign',
    campaignNotes: 'Black Friday weekend activation',
    client: 'American Express',
    eventType: 'Street Team',
    masterProgram: 'Small Business Saturday',
    region: 'National',
    status: 'planning',
    year: 2025,
    month: 11,
    yearMonth: '2025-11',
    campaignOwner: 'lisa.anderson@momentumww.com',
    campaignOwnerEmail: 'lisa.anderson@momentumww.com',
    createdBy: 'lisa.anderson@momentumww.com',
    createdByName: 'Lisa Anderson',
    createdOn: new Date('2025-04-10'),
    jobNumbers: ['AMEX-SBS-2025', 'JOB-45678'],
    visible: true,
  },

  // Verizon 5G Gaming
  {
    id: 'camp-verizon-gaming-001',
    campaignName: 'Verizon 5G Gaming Experience',
    campaignDescription: 'Mobile gaming truck tour with 5G demonstration',
    campaignNotes: 'Partnership with major gaming publishers',
    client: 'Verizon',
    eventType: 'Pop-Up Store',
    masterProgram: '5G Gaming Initiative',
    region: 'Midwest',
    status: 'active',
    year: 2025,
    month: 8,
    yearMonth: '2025-08',
    campaignOwner: 'james.wilson@momentumww.com',
    campaignOwnerEmail: 'james.wilson@momentumww.com',
    createdBy: 'james.wilson@momentumww.com',
    createdByName: 'James Wilson',
    createdOn: new Date('2025-03-20'),
    jobNumbers: ['VZ-GAMING-2025'],
    visible: true,
  },

  // Coca-Cola Concert Series
  {
    id: 'camp-cocacola-concerts-001',
    campaignName: 'Coca-Cola Summer Concert Series',
    campaignDescription: 'Outdoor concert sponsorship series',
    campaignNotes: 'Major amphitheaters, 15 cities',
    client: 'Coca-Cola',
    eventType: 'Concert',
    masterProgram: 'Music Platform',
    region: 'National',
    status: 'active',
    year: 2025,
    month: 6,
    yearMonth: '2025-06',
    campaignOwner: 'maria.garcia@momentumww.com',
    campaignOwnerEmail: 'maria.garcia@momentumww.com',
    createdBy: 'maria.garcia@momentumww.com',
    createdByName: 'Maria Garcia',
    createdOn: new Date('2025-01-20'),
    updatedBy: 'maria.garcia@momentumww.com',
    updatedByName: 'Maria Garcia',
    updatedOn: new Date('2025-03-15'),
    jobNumbers: ['COKE-CONCERTS-2025'],
    visible: true,
  },

  // AMEX Travel Experience
  {
    id: 'camp-amex-travel-001',
    campaignName: 'AMEX Centurion Lounge Openings',
    campaignDescription: 'Launch events for new airport lounge locations',
    campaignNotes: '3 new markets: DFW, SEA, ATL',
    client: 'American Express',
    eventType: 'Corporate Event',
    masterProgram: 'Centurion Expansion',
    region: 'National',
    status: 'active',
    year: 2025,
    month: 10,
    yearMonth: '2025-10',
    campaignOwner: 'robert.taylor@momentumww.com',
    campaignOwnerEmail: 'robert.taylor@momentumww.com',
    createdBy: 'robert.taylor@momentumww.com',
    createdByName: 'Robert Taylor',
    createdOn: new Date('2025-04-05'),
    jobNumbers: ['AMEX-CENT-2025', 'JOB-56789'],
    visible: true,
  },

  // Constellation Modelo
  {
    id: 'camp-modelo-soccer-001',
    campaignName: 'Modelo Soccer Tournament Series',
    campaignDescription: 'Grassroots soccer tournament sponsorship',
    campaignNotes: 'Focus on Hispanic markets',
    client: 'Constellation Brands',
    eventType: 'Sports Activation',
    masterProgram: 'Modelo Sports',
    region: 'Southwest',
    status: 'completed',
    year: 2025,
    month: 4,
    yearMonth: '2025-04',
    campaignOwner: 'amanda.brown@momentumww.com',
    campaignOwnerEmail: 'amanda.brown@momentumww.com',
    createdBy: 'amanda.brown@momentumww.com',
    createdByName: 'Amanda Brown',
    createdOn: new Date('2024-12-01'),
    updatedBy: 'amanda.brown@momentumww.com',
    updatedByName: 'Amanda Brown',
    updatedOn: new Date('2025-05-01'),
    jobNumbers: ['MODELO-SOCCER-2025'],
    visible: true,
  },

  // Verizon Trade Show
  {
    id: 'camp-verizon-ces-001',
    campaignName: 'Verizon CES 2025',
    campaignDescription: 'Consumer Electronics Show booth activation',
    campaignNotes: 'Flagship booth, 5G demos',
    client: 'Verizon',
    eventType: 'Trade Show',
    masterProgram: 'CES Program',
    region: 'West Coast',
    status: 'completed',
    year: 2025,
    month: 1,
    yearMonth: '2025-01',
    campaignOwner: 'christopher.lee@momentumww.com',
    campaignOwnerEmail: 'christopher.lee@momentumww.com',
    createdBy: 'christopher.lee@momentumww.com',
    createdByName: 'Christopher Lee',
    createdOn: new Date('2024-10-01'),
    updatedBy: 'christopher.lee@momentumww.com',
    updatedByName: 'Christopher Lee',
    updatedOn: new Date('2025-01-15'),
    jobNumbers: ['VZ-CES-2025'],
    visible: true,
  },
];

// ============================================================================
// EVENTS (25 events across campaigns)
// ============================================================================

export const mockEvents: Event[] = [
  // AMEX Music Tour Events
  {
    id: 'evt-001',
    campaignId: 'camp-amex-music-001',
    eventName: 'Lollapalooza Chicago',
    eventDetails: 'AMEX Cardholder Lounge + Main Stage Activation',
    eventNotes: '4-day festival, expected 100k+ attendees per day',
    number: '001',
    index: 1,
    eventStartDate: new Date('2025-08-01'),
    eventEndDate: new Date('2025-08-04'),
    year: 2025,
    month: 8,
    yearMonthStart: '2025-08',
    yearMonthEnd: '2025-08',
    eventVenue: 'Grant Park',
    city: 'Chicago',
    country: 'USA',
    postCode: '60601',
    address1: 'Grant Park',
    latitude: 41.8759,
    longitude: -87.6189,
    distanceFromOfficeMi: 715,
    distanceFromOfficeKm: 1150,
    timeFromOfficeMins: 120,
    owner: 'sarah.johnson@momentumww.com',
    ownerName: 'Sarah Johnson',
    status: 'active',
    createdBy: 'sarah.johnson@momentumww.com',
    createdByName: 'Sarah Johnson',
    createdOn: new Date('2025-01-15'),
    updatedBy: 'sarah.johnson@momentumww.com',
    updatedByName: 'Sarah Johnson',
    updatedOn: new Date('2025-03-10'),
  },
  {
    id: 'evt-002',
    campaignId: 'camp-amex-music-001',
    eventName: 'Coachella Weekend 1',
    eventDetails: 'VIP Experience Zone',
    number: '002',
    index: 2,
    eventStartDate: new Date('2025-04-11'),
    eventEndDate: new Date('2025-04-13'),
    year: 2025,
    month: 4,
    yearMonthStart: '2025-04',
    yearMonthEnd: '2025-04',
    eventVenue: 'Empire Polo Club',
    city: 'Indio',
    country: 'USA',
    postCode: '92201',
    latitude: 33.6803,
    longitude: -116.2371,
    distanceFromOfficeMi: 125,
    distanceFromOfficeKm: 201,
    timeFromOfficeMins: 135,
    owner: 'sarah.johnson@momentumww.com',
    ownerName: 'Sarah Johnson',
    status: 'completed',
    createdBy: 'sarah.johnson@momentumww.com',
    createdByName: 'Sarah Johnson',
    createdOn: new Date('2025-01-15'),
  },
  {
    id: 'evt-003',
    campaignId: 'camp-amex-music-001',
    eventName: 'Austin City Limits',
    eventDetails: 'Platinum Cardholder Lounge',
    number: '003',
    index: 3,
    eventStartDate: new Date('2025-10-03'),
    eventEndDate: new Date('2025-10-05'),
    year: 2025,
    month: 10,
    yearMonthStart: '2025-10',
    yearMonthEnd: '2025-10',
    eventVenue: 'Zilker Park',
    city: 'Austin',
    country: 'USA',
    postCode: '78746',
    latitude: 30.2672,
    longitude: -97.7431,
    distanceFromOfficeMi: 1375,
    distanceFromOfficeKm: 2213,
    timeFromOfficeMins: 180,
    owner: 'sarah.johnson@momentumww.com',
    ownerName: 'Sarah Johnson',
    status: 'planning',
    createdBy: 'sarah.johnson@momentumww.com',
    createdByName: 'Sarah Johnson',
    createdOn: new Date('2025-01-15'),
  },

  // Verizon NFL Events
  {
    id: 'evt-004',
    campaignId: 'camp-verizon-nfl-001',
    eventName: 'Giants vs Cowboys - MetLife Stadium',
    eventDetails: '5G Ultra Wideband Fan Experience Zone',
    number: '001',
    index: 1,
    eventStartDate: new Date('2025-09-14'),
    eventEndDate: new Date('2025-09-14'),
    year: 2025,
    month: 9,
    yearMonthStart: '2025-09',
    yearMonthEnd: '2025-09',
    eventVenue: 'MetLife Stadium',
    city: 'East Rutherford',
    country: 'USA',
    postCode: '07073',
    latitude: 40.8128,
    longitude: -74.0742,
    distanceFromOfficeMi: 15,
    distanceFromOfficeKm: 24,
    timeFromOfficeMins: 30,
    owner: 'michael.chen@momentumww.com',
    ownerName: 'Michael Chen',
    status: 'active',
    createdBy: 'michael.chen@momentumww.com',
    createdByName: 'Michael Chen',
    createdOn: new Date('2025-02-01'),
  },
  {
    id: 'evt-005',
    campaignId: 'camp-verizon-nfl-001',
    eventName: 'Patriots vs Bills - Gillette Stadium',
    eventDetails: '5G Demo Truck + Interactive Games',
    number: '002',
    index: 2,
    eventStartDate: new Date('2025-10-05'),
    eventEndDate: new Date('2025-10-05'),
    year: 2025,
    month: 10,
    yearMonthStart: '2025-10',
    yearMonthEnd: '2025-10',
    eventVenue: 'Gillette Stadium',
    city: 'Foxborough',
    country: 'USA',
    postCode: '02035',
    latitude: 42.0909,
    longitude: -71.2643,
    distanceFromOfficeMi: 230,
    distanceFromOfficeKm: 370,
    timeFromOfficeMins: 240,
    owner: 'michael.chen@momentumww.com',
    ownerName: 'Michael Chen',
    status: 'planning',
    createdBy: 'michael.chen@momentumww.com',
    createdByName: 'Michael Chen',
    createdOn: new Date('2025-02-01'),
  },
  {
    id: 'evt-006',
    campaignId: 'camp-verizon-nfl-001',
    eventName: 'Rams vs 49ers - SoFi Stadium',
    eventDetails: '5G Network Experience',
    number: '003',
    index: 3,
    eventStartDate: new Date('2025-11-16'),
    eventEndDate: new Date('2025-11-16'),
    year: 2025,
    month: 11,
    yearMonthStart: '2025-11',
    yearMonthEnd: '2025-11',
    eventVenue: 'SoFi Stadium',
    city: 'Inglewood',
    country: 'USA',
    postCode: '90301',
    latitude: 33.9535,
    longitude: -118.3392,
    distanceFromOfficeMi: 2450,
    distanceFromOfficeKm: 3943,
    timeFromOfficeMins: 300,
    owner: 'michael.chen@momentumww.com',
    ownerName: 'Michael Chen',
    status: 'planning',
    createdBy: 'michael.chen@momentumww.com',
    createdByName: 'Michael Chen',
    createdOn: new Date('2025-02-01'),
  },

  // Coca-Cola Product Sampling Events
  {
    id: 'evt-007',
    campaignId: 'camp-cocacola-sampling-001',
    eventName: 'NYC Bryant Park Sampling',
    eventDetails: 'Pop-up sampling booth + photo activation',
    number: '001',
    index: 1,
    eventStartDate: new Date('2025-07-15'),
    eventEndDate: new Date('2025-07-17'),
    year: 2025,
    month: 7,
    yearMonthStart: '2025-07',
    yearMonthEnd: '2025-07',
    eventVenue: 'Bryant Park',
    city: 'New York',
    country: 'USA',
    postCode: '10018',
    latitude: 40.7536,
    longitude: -73.9832,
    distanceFromOfficeMi: 5,
    distanceFromOfficeKm: 8,
    timeFromOfficeMins: 20,
    owner: 'emily.rodriguez@momentumww.com',
    ownerName: 'Emily Rodriguez',
    status: 'planning',
    createdBy: 'emily.rodriguez@momentumww.com',
    createdByName: 'Emily Rodriguez',
    createdOn: new Date('2025-03-01'),
  },
  {
    id: 'evt-008',
    campaignId: 'camp-cocacola-sampling-001',
    eventName: 'LA Venice Beach Activation',
    eventDetails: 'Beach boardwalk sampling',
    number: '002',
    index: 2,
    eventStartDate: new Date('2025-07-22'),
    eventEndDate: new Date('2025-07-24'),
    year: 2025,
    month: 7,
    yearMonthStart: '2025-07',
    yearMonthEnd: '2025-07',
    eventVenue: 'Venice Beach Boardwalk',
    city: 'Los Angeles',
    country: 'USA',
    postCode: '90291',
    latitude: 33.9850,
    longitude: -118.4695,
    distanceFromOfficeMi: 2460,
    distanceFromOfficeKm: 3959,
    timeFromOfficeMins: 310,
    owner: 'emily.rodriguez@momentumww.com',
    ownerName: 'Emily Rodriguez',
    status: 'planning',
    createdBy: 'emily.rodriguez@momentumww.com',
    createdByName: 'Emily Rodriguez',
    createdOn: new Date('2025-03-01'),
  },
  {
    id: 'evt-009',
    campaignId: 'camp-cocacola-sampling-001',
    eventName: 'Miami South Beach Experience',
    eventDetails: 'Beach day activation with games',
    number: '003',
    index: 3,
    eventStartDate: new Date('2025-08-05'),
    eventEndDate: new Date('2025-08-07'),
    year: 2025,
    month: 8,
    yearMonthStart: '2025-08',
    yearMonthEnd: '2025-08',
    eventVenue: 'South Beach',
    city: 'Miami',
    country: 'USA',
    postCode: '33139',
    latitude: 25.7907,
    longitude: -80.1300,
    distanceFromOfficeMi: 1090,
    distanceFromOfficeKm: 1754,
    timeFromOfficeMins: 180,
    owner: 'emily.rodriguez@momentumww.com',
    ownerName: 'Emily Rodriguez',
    status: 'planning',
    createdBy: 'emily.rodriguez@momentumww.com',
    createdByName: 'Emily Rodriguez',
    createdOn: new Date('2025-03-01'),
  },

  // Corona Beach Events
  {
    id: 'evt-010',
    campaignId: 'camp-corona-beach-001',
    eventName: 'Santa Monica Pier Weekend',
    eventDetails: 'Beach volleyball tournament + sampling',
    number: '001',
    index: 1,
    eventStartDate: new Date('2025-05-24'),
    eventEndDate: new Date('2025-05-26'),
    year: 2025,
    month: 5,
    yearMonthStart: '2025-05',
    yearMonthEnd: '2025-05',
    eventVenue: 'Santa Monica Pier',
    city: 'Santa Monica',
    country: 'USA',
    postCode: '90401',
    latitude: 34.0095,
    longitude: -118.4977,
    distanceFromOfficeMi: 2455,
    distanceFromOfficeKm: 3951,
    timeFromOfficeMins: 305,
    owner: 'david.kim@momentumww.com',
    ownerName: 'David Kim',
    status: 'active',
    createdBy: 'david.kim@momentumww.com',
    createdByName: 'David Kim',
    createdOn: new Date('2025-02-15'),
  },
  {
    id: 'evt-011',
    campaignId: 'camp-corona-beach-001',
    eventName: 'San Diego Mission Beach',
    eventDetails: 'Sunset beach party experience',
    number: '002',
    index: 2,
    eventStartDate: new Date('2025-06-07'),
    eventEndDate: new Date('2025-06-09'),
    year: 2025,
    month: 6,
    yearMonthStart: '2025-06',
    yearMonthEnd: '2025-06',
    eventVenue: 'Mission Beach',
    city: 'San Diego',
    country: 'USA',
    postCode: '92109',
    latitude: 32.7727,
    longitude: -117.2527,
    distanceFromOfficeMi: 2425,
    distanceFromOfficeKm: 3902,
    timeFromOfficeMins: 300,
    owner: 'david.kim@momentumww.com',
    ownerName: 'David Kim',
    status: 'active',
    createdBy: 'david.kim@momentumww.com',
    createdByName: 'David Kim',
    createdOn: new Date('2025-02-15'),
  },

  // Additional events (12 more to reach 25 total)
  {
    id: 'evt-012',
    campaignId: 'camp-verizon-gaming-001',
    eventName: 'Chicago Navy Pier Gaming Expo',
    eventDetails: 'Mobile gaming truck with 5G demos',
    eventStartDate: new Date('2025-08-15'),
    eventEndDate: new Date('2025-08-17'),
    year: 2025,
    month: 8,
    yearMonthStart: '2025-08',
    yearMonthEnd: '2025-08',
    eventVenue: 'Navy Pier',
    city: 'Chicago',
    country: 'USA',
    postCode: '60611',
    latitude: 41.8917,
    longitude: -87.6086,
    owner: 'james.wilson@momentumww.com',
    ownerName: 'James Wilson',
    status: 'active',
    createdBy: 'james.wilson@momentumww.com',
    createdByName: 'James Wilson',
    createdOn: new Date('2025-03-20'),
  },
  {
    id: 'evt-013',
    campaignId: 'camp-verizon-gaming-001',
    eventName: 'Detroit Gaming Convention',
    eventDetails: '5G esports tournament',
    eventStartDate: new Date('2025-09-20'),
    eventEndDate: new Date('2025-09-22'),
    year: 2025,
    month: 9,
    yearMonthStart: '2025-09',
    yearMonthEnd: '2025-09',
    eventVenue: 'Huntington Place',
    city: 'Detroit',
    country: 'USA',
    postCode: '48226',
    latitude: 42.3293,
    longitude: -83.0467,
    owner: 'james.wilson@momentumww.com',
    ownerName: 'James Wilson',
    status: 'planning',
    createdBy: 'james.wilson@momentumww.com',
    createdByName: 'James Wilson',
    createdOn: new Date('2025-03-20'),
  },
  {
    id: 'evt-014',
    campaignId: 'camp-cocacola-concerts-001',
    eventName: 'Red Rocks Amphitheatre Concert',
    eventDetails: 'Coke Studio lounge',
    eventStartDate: new Date('2025-06-28'),
    eventEndDate: new Date('2025-06-28'),
    year: 2025,
    month: 6,
    yearMonthStart: '2025-06',
    yearMonthEnd: '2025-06',
    eventVenue: 'Red Rocks Amphitheatre',
    city: 'Morrison',
    country: 'USA',
    postCode: '80465',
    latitude: 39.6654,
    longitude: -105.2057,
    owner: 'maria.garcia@momentumww.com',
    ownerName: 'Maria Garcia',
    status: 'active',
    createdBy: 'maria.garcia@momentumww.com',
    createdByName: 'Maria Garcia',
    createdOn: new Date('2025-01-20'),
  },
  {
    id: 'evt-015',
    campaignId: 'camp-cocacola-concerts-001',
    eventName: 'Hollywood Bowl Summer Series',
    eventDetails: 'Premium seating area',
    eventStartDate: new Date('2025-07-12'),
    eventEndDate: new Date('2025-07-12'),
    year: 2025,
    month: 7,
    yearMonthStart: '2025-07',
    yearMonthEnd: '2025-07',
    eventVenue: 'Hollywood Bowl',
    city: 'Los Angeles',
    country: 'USA',
    postCode: '90068',
    latitude: 34.1128,
    longitude: -118.3389,
    owner: 'maria.garcia@momentumww.com',
    ownerName: 'Maria Garcia',
    status: 'active',
    createdBy: 'maria.garcia@momentumww.com',
    createdByName: 'Maria Garcia',
    createdOn: new Date('2025-01-20'),
  },
  {
    id: 'evt-016',
    campaignId: 'camp-amex-travel-001',
    eventName: 'DFW Centurion Lounge Grand Opening',
    eventDetails: 'VIP launch event',
    eventStartDate: new Date('2025-10-15'),
    eventEndDate: new Date('2025-10-15'),
    year: 2025,
    month: 10,
    yearMonthStart: '2025-10',
    yearMonthEnd: '2025-10',
    eventVenue: 'DFW Airport Terminal D',
    city: 'Dallas',
    country: 'USA',
    postCode: '75261',
    latitude: 32.8998,
    longitude: -97.0403,
    owner: 'robert.taylor@momentumww.com',
    ownerName: 'Robert Taylor',
    status: 'planning',
    createdBy: 'robert.taylor@momentumww.com',
    createdByName: 'Robert Taylor',
    createdOn: new Date('2025-04-05'),
  },
  {
    id: 'evt-017',
    campaignId: 'camp-amex-travel-001',
    eventName: 'SEA Centurion Lounge Launch',
    eventDetails: 'Soft opening for Platinum cardholders',
    eventStartDate: new Date('2025-11-20'),
    eventEndDate: new Date('2025-11-20'),
    year: 2025,
    month: 11,
    yearMonthStart: '2025-11',
    yearMonthEnd: '2025-11',
    eventVenue: 'Seattle-Tacoma Airport North Satellite',
    city: 'Seattle',
    country: 'USA',
    postCode: '98158',
    latitude: 47.4502,
    longitude: -122.3088,
    owner: 'robert.taylor@momentumww.com',
    ownerName: 'Robert Taylor',
    status: 'planning',
    createdBy: 'robert.taylor@momentumww.com',
    createdByName: 'Robert Taylor',
    createdOn: new Date('2025-04-05'),
  },
  {
    id: 'evt-018',
    campaignId: 'camp-modelo-soccer-001',
    eventName: 'LA Galaxy vs LAFC',
    eventDetails: 'Modelo Fan Zone',
    eventStartDate: new Date('2025-04-19'),
    eventEndDate: new Date('2025-04-19'),
    year: 2025,
    month: 4,
    yearMonthStart: '2025-04',
    yearMonthEnd: '2025-04',
    eventVenue: 'Dignity Health Sports Park',
    city: 'Carson',
    country: 'USA',
    postCode: '90746',
    latitude: 33.8643,
    longitude: -118.2611,
    owner: 'amanda.brown@momentumww.com',
    ownerName: 'Amanda Brown',
    status: 'completed',
    createdBy: 'amanda.brown@momentumww.com',
    createdByName: 'Amanda Brown',
    createdOn: new Date('2024-12-01'),
  },
  {
    id: 'evt-019',
    campaignId: 'camp-modelo-soccer-001',
    eventName: 'Houston Dynamo Tournament',
    eventDetails: 'Youth soccer championship',
    eventStartDate: new Date('2025-04-26'),
    eventEndDate: new Date('2025-04-27'),
    year: 2025,
    month: 4,
    yearMonthStart: '2025-04',
    yearMonthEnd: '2025-04',
    eventVenue: 'Shell Energy Stadium',
    city: 'Houston',
    country: 'USA',
    postCode: '77054',
    latitude: 29.7520,
    longitude: -95.3518,
    owner: 'amanda.brown@momentumww.com',
    ownerName: 'Amanda Brown',
    status: 'completed',
    createdBy: 'amanda.brown@momentumww.com',
    createdByName: 'Amanda Brown',
    createdOn: new Date('2024-12-01'),
  },
  {
    id: 'evt-020',
    campaignId: 'camp-verizon-ces-001',
    eventName: 'CES 2025 - Las Vegas Convention Center',
    eventDetails: 'Main booth + press conferences',
    eventStartDate: new Date('2025-01-07'),
    eventEndDate: new Date('2025-01-10'),
    year: 2025,
    month: 1,
    yearMonthStart: '2025-01',
    yearMonthEnd: '2025-01',
    eventVenue: 'Las Vegas Convention Center',
    city: 'Las Vegas',
    country: 'USA',
    postCode: '89109',
    latitude: 36.1317,
    longitude: -115.1532,
    owner: 'christopher.lee@momentumww.com',
    ownerName: 'Christopher Lee',
    status: 'completed',
    createdBy: 'christopher.lee@momentumww.com',
    createdByName: 'Christopher Lee',
    createdOn: new Date('2024-10-01'),
  },
  {
    id: 'evt-021',
    campaignId: 'camp-amex-biz-001',
    eventName: 'NYC Small Business Saturday',
    eventDetails: 'Street team + merchant support',
    eventStartDate: new Date('2025-11-29'),
    eventEndDate: new Date('2025-11-29'),
    year: 2025,
    month: 11,
    yearMonthStart: '2025-11',
    yearMonthEnd: '2025-11',
    eventVenue: 'Various NYC Neighborhoods',
    city: 'New York',
    country: 'USA',
    postCode: '10001',
    latitude: 40.7484,
    longitude: -73.9857,
    owner: 'lisa.anderson@momentumww.com',
    ownerName: 'Lisa Anderson',
    status: 'planning',
    createdBy: 'lisa.anderson@momentumww.com',
    createdByName: 'Lisa Anderson',
    createdOn: new Date('2025-04-10'),
  },
  {
    id: 'evt-022',
    campaignId: 'camp-amex-biz-001',
    eventName: 'Chicago Small Business Day',
    eventDetails: 'Merchant activation',
    eventStartDate: new Date('2025-11-29'),
    eventEndDate: new Date('2025-11-29'),
    year: 2025,
    month: 11,
    yearMonthStart: '2025-11',
    yearMonthEnd: '2025-11',
    eventVenue: 'Magnificent Mile',
    city: 'Chicago',
    country: 'USA',
    postCode: '60611',
    latitude: 41.8976,
    longitude: -87.6205,
    owner: 'lisa.anderson@momentumww.com',
    ownerName: 'Lisa Anderson',
    status: 'planning',
    createdBy: 'lisa.anderson@momentumww.com',
    createdByName: 'Lisa Anderson',
    createdOn: new Date('2025-04-10'),
  },
  {
    id: 'evt-023',
    campaignId: 'camp-corona-beach-001',
    eventName: 'Huntington Beach Surf Competition',
    eventDetails: 'Corona branded surf contest',
    eventStartDate: new Date('2025-07-19'),
    eventEndDate: new Date('2025-07-21'),
    year: 2025,
    month: 7,
    yearMonthStart: '2025-07',
    yearMonthEnd: '2025-07',
    eventVenue: 'Huntington Beach Pier',
    city: 'Huntington Beach',
    country: 'USA',
    postCode: '92648',
    latitude: 33.6553,
    longitude: -117.9988,
    owner: 'david.kim@momentumww.com',
    ownerName: 'David Kim',
    status: 'active',
    createdBy: 'david.kim@momentumww.com',
    createdByName: 'David Kim',
    createdOn: new Date('2025-02-15'),
  },
  {
    id: 'evt-024',
    campaignId: 'camp-cocacola-sampling-001',
    eventName: 'Dallas Fair Park Activation',
    eventDetails: 'State Fair of Texas sampling',
    eventStartDate: new Date('2025-09-26'),
    eventEndDate: new Date('2025-10-19'),
    year: 2025,
    month: 9,
    yearMonthStart: '2025-09',
    yearMonthEnd: '2025-10',
    eventVenue: 'Fair Park',
    city: 'Dallas',
    country: 'USA',
    postCode: '75210',
    latitude: 32.7856,
    longitude: -96.7656,
    owner: 'emily.rodriguez@momentumww.com',
    ownerName: 'Emily Rodriguez',
    status: 'planning',
    createdBy: 'emily.rodriguez@momentumww.com',
    createdByName: 'Emily Rodriguez',
    createdOn: new Date('2025-03-01'),
  },
  {
    id: 'evt-025',
    campaignId: 'camp-cocacola-concerts-001',
    eventName: 'Madison Square Garden Concert Series',
    eventDetails: 'VIP lounge sponsorship',
    eventStartDate: new Date('2025-08-14'),
    eventEndDate: new Date('2025-08-15'),
    year: 2025,
    month: 8,
    yearMonthStart: '2025-08',
    yearMonthEnd: '2025-08',
    eventVenue: 'Madison Square Garden',
    city: 'New York',
    country: 'USA',
    postCode: '10001',
    latitude: 40.7505,
    longitude: -73.9934,
    owner: 'maria.garcia@momentumww.com',
    ownerName: 'Maria Garcia',
    status: 'active',
    createdBy: 'maria.garcia@momentumww.com',
    createdByName: 'Maria Garcia',
    createdOn: new Date('2025-01-20'),
  },
];

// ============================================================================
// EVENT VENUES (15 major venues linked to events)
// ============================================================================

export const mockEventVenues: Venue[] = [
  {
    id: 'venue-001',
    eventId: 'evt-001',
    name: 'Grant Park',
    fullAddress: 'Grant Park, Chicago, IL 60601, USA',
    formattedAddress: 'Grant Park, Chicago, IL 60601',
    country: 'USA',
    city: 'Chicago',
    state: 'Illinois',
    stateCode: 'IL',
    postCode: '60601',
    address: 'Grant Park',
    latitude: 41.8759,
    longitude: -87.6189,
    platform: 'Google Maps',
    poiScope: 'Public Park',
    entityType: 'Park',
    category: 'Outdoor Venue',
    group: 'Recreation',
    subCategory: 'Urban Park',
    status: 'verified',
    checkedOn: new Date('2025-03-15'),
    count: 5,
    tags: ['festival', 'outdoor', 'large-capacity'],
    url: 'https://www.chicagoparkdistrict.com/parks-facilities/grant-park',
  },
  {
    id: 'venue-002',
    eventId: 'evt-002',
    name: 'Empire Polo Club',
    fullAddress: '81-800 Avenue 51, Indio, CA 92201, USA',
    formattedAddress: '81-800 Avenue 51, Indio, CA 92201',
    country: 'USA',
    city: 'Indio',
    state: 'California',
    stateCode: 'CA',
    postCode: '92201',
    address: '81-800 Avenue 51',
    latitude: 33.6803,
    longitude: -116.2371,
    platform: 'Azure Maps',
    entityType: 'Outdoor Venue',
    category: 'Music Festival Grounds',
    group: 'Entertainment',
    status: 'verified',
    checkedOn: new Date('2025-01-20'),
    count: 2,
    tags: ['coachella', 'music-festival', 'desert'],
    url: 'https://www.empirepoloclub.com',
  },
  {
    id: 'venue-003',
    eventId: 'evt-004',
    name: 'MetLife Stadium',
    fullAddress: '1 MetLife Stadium Dr, East Rutherford, NJ 07073, USA',
    formattedAddress: '1 MetLife Stadium Dr, East Rutherford, NJ 07073',
    country: 'USA',
    city: 'East Rutherford',
    state: 'New Jersey',
    stateCode: 'NJ',
    postCode: '07073',
    address: '1 MetLife Stadium Dr',
    latitude: 40.8128,
    longitude: -74.0742,
    platform: 'Google Maps',
    entityType: 'Stadium',
    category: 'Sports Venue',
    group: 'NFL Stadium',
    subCategory: 'Professional Football',
    status: 'verified',
    checkedOn: new Date('2025-02-10'),
    count: 12,
    tags: ['nfl', 'stadium', 'large-capacity', 'giants', 'jets'],
    url: 'https://www.metlifestadium.com',
  },
  {
    id: 'venue-004',
    eventId: 'evt-005',
    name: 'Gillette Stadium',
    fullAddress: '1 Patriot Pl, Foxborough, MA 02035, USA',
    formattedAddress: '1 Patriot Pl, Foxborough, MA 02035',
    country: 'USA',
    city: 'Foxborough',
    state: 'Massachusetts',
    stateCode: 'MA',
    postCode: '02035',
    address: '1 Patriot Pl',
    latitude: 42.0909,
    longitude: -71.2643,
    platform: 'Google Maps',
    entityType: 'Stadium',
    category: 'Sports Venue',
    group: 'NFL Stadium',
    status: 'verified',
    checkedOn: new Date('2025-02-05'),
    count: 8,
    tags: ['nfl', 'patriots', 'stadium'],
    url: 'https://www.gillettestadium.com',
  },
  {
    id: 'venue-005',
    eventId: 'evt-006',
    name: 'SoFi Stadium',
    fullAddress: '1001 Stadium Dr, Inglewood, CA 90301, USA',
    formattedAddress: '1001 Stadium Dr, Inglewood, CA 90301',
    country: 'USA',
    city: 'Inglewood',
    state: 'California',
    stateCode: 'CA',
    postCode: '90301',
    address: '1001 Stadium Dr',
    latitude: 33.9535,
    longitude: -118.3392,
    platform: 'Azure Maps',
    entityType: 'Stadium',
    category: 'Sports & Entertainment',
    group: 'NFL Stadium',
    status: 'verified',
    checkedOn: new Date('2025-01-25'),
    count: 6,
    tags: ['nfl', 'rams', 'chargers', 'state-of-the-art'],
    url: 'https://www.sofistadium.com',
  },
  {
    id: 'venue-006',
    eventId: 'evt-007',
    name: 'Bryant Park',
    fullAddress: 'Bryant Park, New York, NY 10018, USA',
    formattedAddress: 'Bryant Park, New York, NY 10018',
    country: 'USA',
    city: 'New York',
    state: 'New York',
    stateCode: 'NY',
    postCode: '10018',
    address: 'Bryant Park',
    latitude: 40.7536,
    longitude: -73.9832,
    platform: 'Google Maps',
    entityType: 'Park',
    category: 'Public Park',
    group: 'Urban Recreation',
    status: 'verified',
    checkedOn: new Date('2025-03-01'),
    count: 15,
    tags: ['nyc', 'public-park', 'midtown', 'activation-friendly'],
    url: 'https://bryantpark.org',
  },
  {
    id: 'venue-007',
    eventId: 'evt-008',
    name: 'Venice Beach Boardwalk',
    fullAddress: 'Venice Beach Boardwalk, Los Angeles, CA 90291, USA',
    formattedAddress: 'Venice Beach Boardwalk, Los Angeles, CA 90291',
    country: 'USA',
    city: 'Los Angeles',
    state: 'California',
    stateCode: 'CA',
    postCode: '90291',
    address: 'Ocean Front Walk',
    latitude: 33.9850,
    longitude: -118.4695,
    platform: 'Google Maps',
    entityType: 'Boardwalk',
    category: 'Public Beachfront',
    group: 'Recreation',
    status: 'active',
    count: 7,
    tags: ['beach', 'boardwalk', 'los-angeles', 'high-traffic'],
  },
  {
    id: 'venue-008',
    eventId: 'evt-009',
    name: 'South Beach',
    fullAddress: 'South Beach, Miami Beach, FL 33139, USA',
    formattedAddress: 'South Beach, Miami Beach, FL 33139',
    country: 'USA',
    city: 'Miami',
    state: 'Florida',
    stateCode: 'FL',
    postCode: '33139',
    address: 'Ocean Drive',
    latitude: 25.7907,
    longitude: -80.1300,
    platform: 'Azure Maps',
    entityType: 'Beach',
    category: 'Public Beach',
    group: 'Coastal Recreation',
    status: 'active',
    count: 4,
    tags: ['beach', 'miami', 'south-beach', 'nightlife'],
  },
  {
    id: 'venue-009',
    eventId: 'evt-010',
    name: 'Santa Monica Pier',
    fullAddress: '200 Santa Monica Pier, Santa Monica, CA 90401, USA',
    formattedAddress: '200 Santa Monica Pier, Santa Monica, CA 90401',
    country: 'USA',
    city: 'Santa Monica',
    state: 'California',
    stateCode: 'CA',
    postCode: '90401',
    address: '200 Santa Monica Pier',
    latitude: 34.0095,
    longitude: -118.4977,
    platform: 'Google Maps',
    entityType: 'Pier',
    category: 'Tourist Attraction',
    group: 'Beachfront',
    status: 'verified',
    checkedOn: new Date('2025-02-20'),
    count: 10,
    tags: ['pier', 'beach', 'landmark', 'tourist-attraction'],
    url: 'https://www.santamonicapier.org',
  },
  {
    id: 'venue-010',
    eventId: 'evt-014',
    name: 'Red Rocks Amphitheatre',
    fullAddress: '18300 W Alameda Pkwy, Morrison, CO 80465, USA',
    formattedAddress: '18300 W Alameda Pkwy, Morrison, CO 80465',
    country: 'USA',
    city: 'Morrison',
    state: 'Colorado',
    stateCode: 'CO',
    postCode: '80465',
    address: '18300 W Alameda Pkwy',
    latitude: 39.6654,
    longitude: -105.2057,
    platform: 'Google Maps',
    entityType: 'Amphitheatre',
    category: 'Concert Venue',
    group: 'Outdoor Music Venue',
    status: 'verified',
    checkedOn: new Date('2025-01-30'),
    count: 20,
    tags: ['concert', 'amphitheatre', 'iconic', 'natural-venue'],
    url: 'https://www.redrocksonline.com',
  },
  {
    id: 'venue-011',
    eventId: 'evt-015',
    name: 'Hollywood Bowl',
    fullAddress: '2301 N Highland Ave, Los Angeles, CA 90068, USA',
    formattedAddress: '2301 N Highland Ave, Los Angeles, CA 90068',
    country: 'USA',
    city: 'Los Angeles',
    state: 'California',
    stateCode: 'CA',
    postCode: '90068',
    address: '2301 N Highland Ave',
    latitude: 34.1128,
    longitude: -118.3389,
    platform: 'Azure Maps',
    entityType: 'Amphitheatre',
    category: 'Music Venue',
    group: 'Historic Venue',
    status: 'verified',
    checkedOn: new Date('2025-02-01'),
    count: 18,
    tags: ['concert', 'historic', 'los-angeles', 'amphitheatre'],
    url: 'https://www.hollywoodbowl.com',
  },
  {
    id: 'venue-012',
    eventId: 'evt-020',
    name: 'Las Vegas Convention Center',
    fullAddress: '3150 Paradise Rd, Las Vegas, NV 89109, USA',
    formattedAddress: '3150 Paradise Rd, Las Vegas, NV 89109',
    country: 'USA',
    city: 'Las Vegas',
    state: 'Nevada',
    stateCode: 'NV',
    postCode: '89109',
    address: '3150 Paradise Rd',
    latitude: 36.1317,
    longitude: -115.1532,
    platform: 'Google Maps',
    entityType: 'Convention Center',
    category: 'Trade Show Venue',
    group: 'Convention Facility',
    status: 'verified',
    checkedOn: new Date('2024-12-15'),
    count: 25,
    tags: ['convention', 'trade-show', 'ces', 'las-vegas'],
    url: 'https://www.vegasmeansbusiness.com',
  },
  {
    id: 'venue-013',
    eventId: 'evt-012',
    name: 'Navy Pier',
    fullAddress: '600 E Grand Ave, Chicago, IL 60611, USA',
    formattedAddress: '600 E Grand Ave, Chicago, IL 60611',
    country: 'USA',
    city: 'Chicago',
    state: 'Illinois',
    stateCode: 'IL',
    postCode: '60611',
    address: '600 E Grand Ave',
    latitude: 41.8917,
    longitude: -87.6086,
    platform: 'Google Maps',
    entityType: 'Pier',
    category: 'Entertainment Complex',
    group: 'Tourist Attraction',
    status: 'verified',
    checkedOn: new Date('2025-03-20'),
    count: 9,
    tags: ['pier', 'chicago', 'waterfront', 'family-friendly'],
    url: 'https://navypier.org',
  },
  {
    id: 'venue-014',
    eventId: 'evt-025',
    name: 'Madison Square Garden',
    fullAddress: '4 Pennsylvania Plaza, New York, NY 10001, USA',
    formattedAddress: '4 Pennsylvania Plaza, New York, NY 10001',
    country: 'USA',
    city: 'New York',
    state: 'New York',
    stateCode: 'NY',
    postCode: '10001',
    address: '4 Pennsylvania Plaza',
    latitude: 40.7505,
    longitude: -73.9934,
    platform: 'Azure Maps',
    entityType: 'Arena',
    category: 'Sports & Entertainment',
    group: 'Indoor Arena',
    status: 'verified',
    checkedOn: new Date('2025-01-18'),
    count: 30,
    tags: ['arena', 'iconic', 'nyc', 'msg', 'world-famous'],
    url: 'https://www.msg.com',
  },
  {
    id: 'venue-015',
    eventId: 'evt-024',
    name: 'Fair Park',
    fullAddress: '3809 Grand Ave, Dallas, TX 75210, USA',
    formattedAddress: '3809 Grand Ave, Dallas, TX 75210',
    country: 'USA',
    city: 'Dallas',
    state: 'Texas',
    stateCode: 'TX',
    postCode: '75210',
    address: '3809 Grand Ave',
    latitude: 32.7856,
    longitude: -96.7656,
    platform: 'Google Maps',
    entityType: 'Fairground',
    category: 'Event Complex',
    group: 'Fair & Exposition',
    status: 'active',
    count: 5,
    tags: ['fairground', 'dallas', 'state-fair', 'large-venue'],
    url: 'https://fairpark.org',
  },
];

// ============================================================================
// PEOPLE ASSIGNMENTS (30 assignments across events)
// ============================================================================

export const mockPeopleAssignments: PeopleAssignment[] = [
  // Lollapalooza Chicago (evt-001) - Large team
  {
    id: 'assign-001',
    eventId: 'evt-001',
    userId: 'user-001',
    userName: 'Jessica Martinez',
    userEmail: 'jessica.martinez@momentumww.com',
    userDepartment: 'Experiential',
    userRole: 'Event Manager',
    onSite: true,
    distanceFromOfficeMi: 715,
    distanceFromOfficeKm: 1150,
    timeFromOfficeMins: 120,
    managerName: 'Sarah Johnson',
    managerEmail: 'sarah.johnson@momentumww.com',
    managerRole: 'Account Director',
    assignedByName: 'Sarah Johnson',
    assignedByEmail: 'sarah.johnson@momentumww.com',
    assignedOn: new Date('2025-02-01'),
  },
  {
    id: 'assign-002',
    eventId: 'evt-001',
    userId: 'user-002',
    userName: 'Kevin Thompson',
    userEmail: 'kevin.thompson@momentumww.com',
    userDepartment: 'Experiential',
    userRole: 'Field Manager',
    onSite: true,
    distanceFromOfficeMi: 715,
    distanceFromOfficeKm: 1150,
    timeFromOfficeMins: 120,
    managerName: 'Jessica Martinez',
    managerEmail: 'jessica.martinez@momentumww.com',
    managerRole: 'Event Manager',
    assignedByName: 'Jessica Martinez',
    assignedByEmail: 'jessica.martinez@momentumww.com',
    assignedOn: new Date('2025-02-05'),
  },
  {
    id: 'assign-003',
    eventId: 'evt-001',
    userId: 'user-003',
    userName: 'Alicia Chen',
    userEmail: 'alicia.chen@momentumww.com',
    userDepartment: 'Experiential',
    userRole: 'Brand Ambassador',
    onSite: true,
    distanceFromOfficeMi: 715,
    distanceFromOfficeKm: 1150,
    timeFromOfficeMins: 120,
    managerName: 'Kevin Thompson',
    managerEmail: 'kevin.thompson@momentumww.com',
    managerRole: 'Field Manager',
    assignedByName: 'Kevin Thompson',
    assignedByEmail: 'kevin.thompson@momentumww.com',
    assignedOn: new Date('2025-02-10'),
  },
  {
    id: 'assign-004',
    eventId: 'evt-001',
    userId: 'user-004',
    userName: 'Brandon Lee',
    userEmail: 'brandon.lee@momentumww.com',
    userDepartment: 'Experiential',
    userRole: 'Brand Ambassador',
    onSite: true,
    distanceFromOfficeMi: 715,
    distanceFromOfficeKm: 1150,
    timeFromOfficeMins: 120,
    managerName: 'Kevin Thompson',
    managerEmail: 'kevin.thompson@momentumww.com',
    managerRole: 'Field Manager',
    assignedByName: 'Kevin Thompson',
    assignedByEmail: 'kevin.thompson@momentumww.com',
    assignedOn: new Date('2025-02-10'),
  },
  {
    id: 'assign-005',
    eventId: 'evt-001',
    userId: 'user-005',
    userName: 'Samantha Wright',
    userEmail: 'samantha.wright@momentumww.com',
    userDepartment: 'Operations',
    userRole: 'Logistics Coordinator',
    onSite: false, // Remote support
    managerName: 'Jessica Martinez',
    managerEmail: 'jessica.martinez@momentumww.com',
    managerRole: 'Event Manager',
    assignedByName: 'Jessica Martinez',
    assignedByEmail: 'jessica.martinez@momentumww.com',
    assignedOn: new Date('2025-02-01'),
  },

  // Giants vs Cowboys (evt-004) - Verizon team
  {
    id: 'assign-006',
    eventId: 'evt-004',
    userId: 'user-006',
    userName: 'Derek Williams',
    userEmail: 'derek.williams@momentumww.com',
    userDepartment: 'Sports Marketing',
    userRole: 'Event Manager',
    onSite: true,
    distanceFromOfficeMi: 15,
    distanceFromOfficeKm: 24,
    timeFromOfficeMins: 30,
    managerName: 'Michael Chen',
    managerEmail: 'michael.chen@momentumww.com',
    managerRole: 'Campaign Lead',
    assignedByName: 'Michael Chen',
    assignedByEmail: 'michael.chen@momentumww.com',
    assignedOn: new Date('2025-02-15'),
  },
  {
    id: 'assign-007',
    eventId: 'evt-004',
    userId: 'user-007',
    userName: 'Natalie Rodriguez',
    userEmail: 'natalie.rodriguez@momentumww.com',
    userDepartment: 'Sports Marketing',
    userRole: 'Brand Ambassador',
    onSite: true,
    distanceFromOfficeMi: 15,
    distanceFromOfficeKm: 24,
    timeFromOfficeMins: 30,
    managerName: 'Derek Williams',
    managerEmail: 'derek.williams@momentumww.com',
    managerRole: 'Event Manager',
    assignedByName: 'Derek Williams',
    assignedByEmail: 'derek.williams@momentumww.com',
    assignedOn: new Date('2025-02-20'),
  },
  {
    id: 'assign-008',
    eventId: 'evt-004',
    userId: 'user-008',
    userName: 'Tyler Johnson',
    userEmail: 'tyler.johnson@momentumww.com',
    userDepartment: 'Technology',
    userRole: 'Tech Specialist',
    onSite: true,
    distanceFromOfficeMi: 15,
    distanceFromOfficeKm: 24,
    timeFromOfficeMins: 30,
    managerName: 'Derek Williams',
    managerEmail: 'derek.williams@momentumww.com',
    managerRole: 'Event Manager',
    assignedByName: 'Derek Williams',
    assignedByEmail: 'derek.williams@momentumww.com',
    assignedOn: new Date('2025-02-20'),
  },

  // NYC Bryant Park (evt-007) - Coca-Cola sampling
  {
    id: 'assign-009',
    eventId: 'evt-007',
    userId: 'user-009',
    userName: 'Rachel Green',
    userEmail: 'rachel.green@momentumww.com',
    userDepartment: 'Sampling',
    userRole: 'Field Manager',
    onSite: true,
    distanceFromOfficeMi: 5,
    distanceFromOfficeKm: 8,
    timeFromOfficeMins: 20,
    managerName: 'Emily Rodriguez',
    managerEmail: 'emily.rodriguez@momentumww.com',
    managerRole: 'Campaign Manager',
    assignedByName: 'Emily Rodriguez',
    assignedByEmail: 'emily.rodriguez@momentumww.com',
    assignedOn: new Date('2025-03-15'),
  },
  {
    id: 'assign-010',
    eventId: 'evt-007',
    userId: 'user-010',
    userName: 'Marcus Davis',
    userEmail: 'marcus.davis@momentumww.com',
    userDepartment: 'Sampling',
    userRole: 'Brand Ambassador',
    onSite: true,
    distanceFromOfficeMi: 5,
    distanceFromOfficeKm: 8,
    timeFromOfficeMins: 20,
    managerName: 'Rachel Green',
    managerEmail: 'rachel.green@momentumww.com',
    managerRole: 'Field Manager',
    assignedByName: 'Rachel Green',
    assignedByEmail: 'rachel.green@momentumww.com',
    assignedOn: new Date('2025-03-18'),
  },

  // Corona Beach Tour (evt-010, evt-011) - Multiple events
  {
    id: 'assign-011',
    eventId: 'evt-010',
    userId: 'user-011',
    userName: 'Sophia Martinez',
    userEmail: 'sophia.martinez@momentumww.com',
    userDepartment: 'Beverage Marketing',
    userRole: 'Event Manager',
    onSite: true,
    distanceFromOfficeMi: 2455,
    distanceFromOfficeKm: 3951,
    timeFromOfficeMins: 305,
    managerName: 'David Kim',
    managerEmail: 'david.kim@momentumww.com',
    managerRole: 'Campaign Lead',
    assignedByName: 'David Kim',
    assignedByEmail: 'david.kim@momentumww.com',
    assignedOn: new Date('2025-02-20'),
  },
  {
    id: 'assign-012',
    eventId: 'evt-010',
    userId: 'user-012',
    userName: 'Carlos Hernandez',
    userEmail: 'carlos.hernandez@momentumww.com',
    userDepartment: 'Beverage Marketing',
    userRole: 'Brand Ambassador',
    onSite: true,
    distanceFromOfficeMi: 2455,
    distanceFromOfficeKm: 3951,
    timeFromOfficeMins: 305,
    managerName: 'Sophia Martinez',
    managerEmail: 'sophia.martinez@momentumww.com',
    managerRole: 'Event Manager',
    assignedByName: 'Sophia Martinez',
    assignedByEmail: 'sophia.martinez@momentumww.com',
    assignedOn: new Date('2025-02-22'),
  },
  {
    id: 'assign-013',
    eventId: 'evt-011',
    userId: 'user-011',
    userName: 'Sophia Martinez',
    userEmail: 'sophia.martinez@momentumww.com',
    userDepartment: 'Beverage Marketing',
    userRole: 'Event Manager',
    onSite: true,
    distanceFromOfficeMi: 2425,
    distanceFromOfficeKm: 3902,
    timeFromOfficeMins: 300,
    managerName: 'David Kim',
    managerEmail: 'david.kim@momentumww.com',
    managerRole: 'Campaign Lead',
    assignedByName: 'David Kim',
    assignedByEmail: 'david.kim@momentumww.com',
    assignedOn: new Date('2025-02-20'),
  },

  // Additional assignments (30 total - continuing pattern)
  {
    id: 'assign-014',
    eventId: 'evt-012',
    userId: 'user-013',
    userName: 'Eric Thompson',
    userEmail: 'eric.thompson@momentumww.com',
    userDepartment: 'Gaming',
    userRole: 'Event Manager',
    onSite: true,
    managerName: 'James Wilson',
    managerEmail: 'james.wilson@momentumww.com',
    managerRole: 'Campaign Lead',
    assignedByName: 'James Wilson',
    assignedByEmail: 'james.wilson@momentumww.com',
    assignedOn: new Date('2025-03-25'),
  },
  {
    id: 'assign-015',
    eventId: 'evt-012',
    userId: 'user-014',
    userName: 'Maya Patel',
    userEmail: 'maya.patel@momentumww.com',
    userDepartment: 'Gaming',
    userRole: 'Brand Ambassador',
    onSite: true,
    managerName: 'Eric Thompson',
    managerEmail: 'eric.thompson@momentumww.com',
    managerRole: 'Event Manager',
    assignedByName: 'Eric Thompson',
    assignedByEmail: 'eric.thompson@momentumww.com',
    assignedOn: new Date('2025-03-28'),
  },
  {
    id: 'assign-016',
    eventId: 'evt-014',
    userId: 'user-015',
    userName: 'Jordan Smith',
    userEmail: 'jordan.smith@momentumww.com',
    userDepartment: 'Music Marketing',
    userRole: 'Field Manager',
    onSite: true,
    managerName: 'Maria Garcia',
    managerEmail: 'maria.garcia@momentumww.com',
    managerRole: 'Campaign Manager',
    assignedByName: 'Maria Garcia',
    assignedByEmail: 'maria.garcia@momentumww.com',
    assignedOn: new Date('2025-01-25'),
  },
  {
    id: 'assign-017',
    eventId: 'evt-014',
    userId: 'user-016',
    userName: 'Ashley Brown',
    userEmail: 'ashley.brown@momentumww.com',
    userDepartment: 'Music Marketing',
    userRole: 'Brand Ambassador',
    onSite: true,
    managerName: 'Jordan Smith',
    managerEmail: 'jordan.smith@momentumww.com',
    managerRole: 'Field Manager',
    assignedByName: 'Jordan Smith',
    assignedByEmail: 'jordan.smith@momentumww.com',
    assignedOn: new Date('2025-01-28'),
  },
  {
    id: 'assign-018',
    eventId: 'evt-015',
    userId: 'user-017',
    userName: 'Chris Anderson',
    userEmail: 'chris.anderson@momentumww.com',
    userDepartment: 'Music Marketing',
    userRole: 'Event Manager',
    onSite: true,
    managerName: 'Maria Garcia',
    managerEmail: 'maria.garcia@momentumww.com',
    managerRole: 'Campaign Manager',
    assignedByName: 'Maria Garcia',
    assignedByEmail: 'maria.garcia@momentumww.com',
    assignedOn: new Date('2025-01-25'),
  },
  {
    id: 'assign-019',
    eventId: 'evt-016',
    userId: 'user-018',
    userName: 'Nicole White',
    userEmail: 'nicole.white@momentumww.com',
    userDepartment: 'Premium Services',
    userRole: 'Event Manager',
    onSite: true,
    managerName: 'Robert Taylor',
    managerEmail: 'robert.taylor@momentumww.com',
    managerRole: 'Campaign Lead',
    assignedByName: 'Robert Taylor',
    assignedByEmail: 'robert.taylor@momentumww.com',
    assignedOn: new Date('2025-04-10'),
  },
  {
    id: 'assign-020',
    eventId: 'evt-018',
    userId: 'user-019',
    userName: 'Diego Ramirez',
    userEmail: 'diego.ramirez@momentumww.com',
    userDepartment: 'Sports Marketing',
    userRole: 'Field Manager',
    onSite: true,
    managerName: 'Amanda Brown',
    managerEmail: 'amanda.brown@momentumww.com',
    managerRole: 'Campaign Manager',
    assignedByName: 'Amanda Brown',
    assignedByEmail: 'amanda.brown@momentumww.com',
    assignedOn: new Date('2024-12-10'),
  },
  // ... Continue pattern to reach 30 total assignments
  {
    id: 'assign-021',
    eventId: 'evt-020',
    userId: 'user-020',
    userName: 'Victoria Kim',
    userEmail: 'victoria.kim@momentumww.com',
    userDepartment: 'Trade Shows',
    userRole: 'Event Manager',
    onSite: true,
    managerName: 'Christopher Lee',
    managerEmail: 'christopher.lee@momentumww.com',
    managerRole: 'Campaign Lead',
    assignedByName: 'Christopher Lee',
    assignedByEmail: 'christopher.lee@momentumww.com',
    assignedOn: new Date('2024-11-01'),
  },
  {
    id: 'assign-022',
    eventId: 'evt-020',
    userId: 'user-021',
    userName: 'Ryan Foster',
    userEmail: 'ryan.foster@momentumww.com',
    userDepartment: 'Technology',
    userRole: 'Tech Specialist',
    onSite: true,
    managerName: 'Victoria Kim',
    managerEmail: 'victoria.kim@momentumww.com',
    managerRole: 'Event Manager',
    assignedByName: 'Victoria Kim',
    assignedByEmail: 'victoria.kim@momentumww.com',
    assignedOn: new Date('2024-11-05'),
  },
  {
    id: 'assign-023',
    eventId: 'evt-021',
    userId: 'user-022',
    userName: 'Hannah Miller',
    userEmail: 'hannah.miller@momentumww.com',
    userDepartment: 'Street Team',
    userRole: 'Team Lead',
    onSite: true,
    distanceFromOfficeMi: 0,
    distanceFromOfficeKm: 0,
    timeFromOfficeMins: 0,
    managerName: 'Lisa Anderson',
    managerEmail: 'lisa.anderson@momentumww.com',
    managerRole: 'Campaign Manager',
    assignedByName: 'Lisa Anderson',
    assignedByEmail: 'lisa.anderson@momentumww.com',
    assignedOn: new Date('2025-04-15'),
  },
  {
    id: 'assign-024',
    eventId: 'evt-021',
    userId: 'user-023',
    userName: 'Jason Park',
    userEmail: 'jason.park@momentumww.com',
    userDepartment: 'Street Team',
    userRole: 'Brand Ambassador',
    onSite: true,
    distanceFromOfficeMi: 0,
    distanceFromOfficeKm: 0,
    timeFromOfficeMins: 0,
    managerName: 'Hannah Miller',
    managerEmail: 'hannah.miller@momentumww.com',
    managerRole: 'Team Lead',
    assignedByName: 'Hannah Miller',
    assignedByEmail: 'hannah.miller@momentumww.com',
    assignedOn: new Date('2025-04-18'),
  },
  {
    id: 'assign-025',
    eventId: 'evt-022',
    userId: 'user-024',
    userName: 'Isabella Torres',
    userEmail: 'isabella.torres@momentumww.com',
    userDepartment: 'Street Team',
    userRole: 'Team Lead',
    onSite: true,
    managerName: 'Lisa Anderson',
    managerEmail: 'lisa.anderson@momentumww.com',
    managerRole: 'Campaign Manager',
    assignedByName: 'Lisa Anderson',
    assignedByEmail: 'lisa.anderson@momentumww.com',
    assignedOn: new Date('2025-04-15'),
  },
  {
    id: 'assign-026',
    eventId: 'evt-023',
    userId: 'user-025',
    userName: 'Alex Rivera',
    userEmail: 'alex.rivera@momentumww.com',
    userDepartment: 'Beverage Marketing',
    userRole: 'Event Manager',
    onSite: true,
    managerName: 'David Kim',
    managerEmail: 'david.kim@momentumww.com',
    managerRole: 'Campaign Lead',
    assignedByName: 'David Kim',
    assignedByEmail: 'david.kim@momentumww.com',
    assignedOn: new Date('2025-02-25'),
  },
  {
    id: 'assign-027',
    eventId: 'evt-024',
    userId: 'user-026',
    userName: 'Madison Cooper',
    userEmail: 'madison.cooper@momentumww.com',
    userDepartment: 'Sampling',
    userRole: 'Field Manager',
    onSite: true,
    managerName: 'Emily Rodriguez',
    managerEmail: 'emily.rodriguez@momentumww.com',
    managerRole: 'Campaign Manager',
    assignedByName: 'Emily Rodriguez',
    assignedByEmail: 'emily.rodriguez@momentumww.com',
    assignedOn: new Date('2025-03-20'),
  },
  {
    id: 'assign-028',
    eventId: 'evt-025',
    userId: 'user-027',
    userName: 'Ethan Brooks',
    userEmail: 'ethan.brooks@momentumww.com',
    userDepartment: 'Music Marketing',
    userRole: 'Event Manager',
    onSite: true,
    distanceFromOfficeMi: 3,
    distanceFromOfficeKm: 5,
    timeFromOfficeMins: 15,
    managerName: 'Maria Garcia',
    managerEmail: 'maria.garcia@momentumww.com',
    managerRole: 'Campaign Manager',
    assignedByName: 'Maria Garcia',
    assignedByEmail: 'maria.garcia@momentumww.com',
    assignedOn: new Date('2025-01-25'),
  },
  {
    id: 'assign-029',
    eventId: 'evt-025',
    userId: 'user-028',
    userName: 'Olivia Bennett',
    userEmail: 'olivia.bennett@momentumww.com',
    userDepartment: 'Music Marketing',
    userRole: 'Brand Ambassador',
    onSite: true,
    distanceFromOfficeMi: 3,
    distanceFromOfficeKm: 5,
    timeFromOfficeMins: 15,
    managerName: 'Ethan Brooks',
    managerEmail: 'ethan.brooks@momentumww.com',
    managerRole: 'Event Manager',
    assignedByName: 'Ethan Brooks',
    assignedByEmail: 'ethan.brooks@momentumww.com',
    assignedOn: new Date('2025-01-28'),
  },
  {
    id: 'assign-030',
    eventId: 'evt-002',
    userId: 'user-029',
    userName: 'Noah Sullivan',
    userEmail: 'noah.sullivan@momentumww.com',
    userDepartment: 'Experiential',
    userRole: 'Event Manager',
    onSite: true,
    distanceFromOfficeMi: 125,
    distanceFromOfficeKm: 201,
    timeFromOfficeMins: 135,
    managerName: 'Sarah Johnson',
    managerEmail: 'sarah.johnson@momentumww.com',
    managerRole: 'Account Director',
    assignedByName: 'Sarah Johnson',
    assignedByEmail: 'sarah.johnson@momentumww.com',
    assignedOn: new Date('2025-01-18'),
  },
];

// ============================================================================
// QR CODES (10 codes for various events)
// ============================================================================

export const mockQRCodes: QRCode[] = [
  {
    id: 'qr-001',
    eventId: 'evt-001',
    codeData: 'https://amexunstaged.com/lollapalooza-2025',
    generatedOn: new Date('2025-07-01'),
    scanCount: 4523,
    qrtigerId: 'QRT-LOL-2025-001',
    qrtigerLastSync: new Date('2025-08-05'),
    qrtigerPath: '/api/v1/qr/QRT-LOL-2025-001',
    qrtigerStatus: 'active',
  },
  {
    id: 'qr-002',
    eventId: 'evt-002',
    codeData: 'https://amexunstaged.com/coachella-2025',
    generatedOn: new Date('2025-03-15'),
    scanCount: 8921,
    qrtigerId: 'QRT-COACH-2025-001',
    qrtigerLastSync: new Date('2025-04-14'),
    qrtigerPath: '/api/v1/qr/QRT-COACH-2025-001',
    qrtigerStatus: 'archived',
  },
  {
    id: 'qr-003',
    eventId: 'evt-004',
    codeData: 'https://verizon5g.com/giants-game',
    generatedOn: new Date('2025-08-15'),
    scanCount: 2145,
    qrtigerId: 'QRT-VZ-NYG-001',
    qrtigerLastSync: new Date('2025-09-15'),
    qrtigerPath: '/api/v1/qr/QRT-VZ-NYG-001',
    qrtigerStatus: 'active',
  },
  {
    id: 'qr-004',
    eventId: 'evt-007',
    codeData: 'https://cocacola.com/zero-sugar-nyc',
    generatedOn: new Date('2025-07-01'),
    scanCount: 1823,
    qrtigerId: 'QRT-COKE-NYC-001',
    qrtigerLastSync: new Date('2025-07-18'),
    qrtigerPath: '/api/v1/qr/QRT-COKE-NYC-001',
    qrtigerStatus: 'active',
  },
  {
    id: 'qr-005',
    eventId: 'evt-010',
    codeData: 'https://corona.com/beach-tour-santa-monica',
    generatedOn: new Date('2025-05-01'),
    scanCount: 3456,
    qrtigerId: 'QRT-CORONA-SM-001',
    qrtigerLastSync: new Date('2025-05-27'),
    qrtigerPath: '/api/v1/qr/QRT-CORONA-SM-001',
    qrtigerStatus: 'active',
  },
  {
    id: 'qr-006',
    eventId: 'evt-012',
    codeData: 'https://verizon5g.com/gaming-expo-chicago',
    generatedOn: new Date('2025-07-20'),
    scanCount: 1234,
    qrtigerId: 'QRT-VZ-CHI-GAMING-001',
    qrtigerLastSync: new Date('2025-08-18'),
    qrtigerPath: '/api/v1/qr/QRT-VZ-CHI-GAMING-001',
    qrtigerStatus: 'active',
  },
  {
    id: 'qr-007',
    eventId: 'evt-014',
    codeData: 'https://cocacola.com/music-redrocks',
    generatedOn: new Date('2025-06-01'),
    scanCount: 5678,
    qrtigerId: 'QRT-COKE-RR-001',
    qrtigerLastSync: new Date('2025-06-29'),
    qrtigerPath: '/api/v1/qr/QRT-COKE-RR-001',
    qrtigerStatus: 'active',
  },
  {
    id: 'qr-008',
    eventId: 'evt-020',
    codeData: 'https://verizon.com/ces-2025',
    generatedOn: new Date('2024-12-15'),
    scanCount: 12456,
    qrtigerId: 'QRT-VZ-CES-001',
    qrtigerLastSync: new Date('2025-01-11'),
    qrtigerPath: '/api/v1/qr/QRT-VZ-CES-001',
    qrtigerStatus: 'archived',
  },
  {
    id: 'qr-009',
    eventId: 'evt-021',
    codeData: 'https://amex.com/small-business-saturday-nyc',
    generatedOn: new Date('2025-11-15'),
    scanCount: 0,
    qrtigerId: 'QRT-AMEX-SBS-NYC-001',
    qrtigerStatus: 'active',
  },
  {
    id: 'qr-010',
    eventId: 'evt-025',
    codeData: 'https://cocacola.com/msg-concert-series',
    generatedOn: new Date('2025-07-25'),
    scanCount: 3821,
    qrtigerId: 'QRT-COKE-MSG-001',
    qrtigerLastSync: new Date('2025-08-16'),
    qrtigerPath: '/api/v1/qr/QRT-COKE-MSG-001',
    qrtigerStatus: 'active',
  },
];

// ============================================================================
// STATISTICS & ANALYTICS
// ============================================================================

export const mockCampaignStatistics: CampaignStatistics = {
  totalCampaigns: mockCampaigns.length,
  activeCampaigns: mockCampaigns.filter(c => c.status === 'active').length,
  totalEvents: mockEvents.length,
  upcomingEvents: mockEvents.filter(e => e.eventStartDate > new Date()).length,
  totalPeopleAssignments: mockPeopleAssignments.length,
  totalQRCodeScans: mockQRCodes.reduce((sum, qr) => sum + qr.scanCount, 0),
  campaignsByClient: {
    'American Express': 3,
    'Verizon': 3,
    'Coca-Cola': 2,
    'Constellation Brands': 2,
  },
  eventsByMonth: [
    { month: '2025-01', count: 1 },
    { month: '2025-04', count: 3 },
    { month: '2025-05', count: 2 },
    { month: '2025-06', count: 3 },
    { month: '2025-07', count: 4 },
    { month: '2025-08', count: 5 },
    { month: '2025-09', count: 3 },
    { month: '2025-10', count: 3 },
    { month: '2025-11', count: 4 },
  ],
};

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Get campaigns by client
 */
export function getCampaignsByClient(client: string): Campaign[] {
  return mockCampaigns.filter(c => c.client === client);
}

/**
 * Get events by campaign
 */
export function getEventsByCampaign(campaignId: string): Event[] {
  return mockEvents.filter(e => e.campaignId === campaignId);
}

/**
 * Get active campaigns
 */
export function getActiveCampaigns(): Campaign[] {
  return mockCampaigns.filter(c => c.status === 'active');
}

/**
 * Get upcoming events
 */
export function getUpcomingEvents(): Event[] {
  const now = new Date();
  return mockEvents.filter(e => e.eventStartDate > now).sort((a, b) =>
    a.eventStartDate.getTime() - b.eventStartDate.getTime()
  );
}

/**
 * Get people assignments for an event
 */
export function getPeopleByEvent(eventId: string): PeopleAssignment[] {
  return mockPeopleAssignments.filter(p => p.eventId === eventId);
}

/**
 * Get QR codes for an event
 */
export function getQRCodeByEvent(eventId: string): QRCode | undefined {
  return mockQRCodes.find(qr => qr.eventId === eventId);
}

/**
 * Get total QR scan count
 */
export function getTotalQRScans(): number {
  return mockQRCodes.reduce((sum, qr) => sum + qr.scanCount, 0);
}

/**
 * Get tickets by type
 */
export function getTicketsByType(type: HelixTicket['type']): HelixTicket[] {
  return mockHelixTickets.filter((t) => t.type === type);
}

/**
 * Get freeze period tickets
 */
export function getFreezePeriodTickets(): HelixTicket[] {
  return mockHelixTickets.filter((t) => t.scheduledAction !== undefined);
}

/**
 * Get open tickets
 */
export function getOpenTickets(): HelixTicket[] {
  return getTicketsByStatus('open');
}

/**
 * Get in-progress tickets
 */
export function getInProgressTickets(): HelixTicket[] {
  return getTicketsByStatus('in-progress');
}

/**
 * Get resolved tickets
 */
export function getResolvedTickets(): HelixTicket[] {
  return [...getTicketsByStatus('resolved'), ...getTicketsByStatus('closed')];
}

// ============================================================================
// APPROVAL STATISTICS
// ============================================================================

export const mockApprovalStatistics = {
  totalPending: getPendingApprovals().length,
  totalApproved: getApprovedApprovals().length,
  totalRejected: getRejectedApprovals().length,
  approvedToday: 2,
  rejectedToday: 1,
  averageApprovalTime: 4.5, // hours
  openTickets: getOpenTickets().length,
  inProgressTickets: getInProgressTickets().length,
  resolvedTickets: getResolvedTickets().length,
  freezePeriodTickets: getFreezePeriodTickets().length,
};

// ============================================================================
// UXP PLATFORM - VENUES
// ============================================================================
// Reusable venue database for experiential events and field marketing

export const mockVenues: Venue[] = [
  // Stadium venues
  {
    id: 'ven-001',
    name: 'MetLife Stadium',
    fullAddress: '1 MetLife Stadium Dr, East Rutherford, NJ 07073, USA',
    formattedAddress: 'MetLife Stadium, East Rutherford, NJ 07073',
    country: 'USA',
    city: 'East Rutherford',
    state: 'New Jersey',
    stateCode: 'NJ',
    postCode: '07073',
    address: '1 MetLife Stadium Dr',
    latitude: 40.8128,
    longitude: -74.0742,
    category: 'Stadium',
    platform: 'Google Maps',
    poiScope: 'Sports & Entertainment',
    entityType: 'Sports Stadium',
    subCategory: 'NFL Stadium',
    tags: ['sports', 'football', 'concerts', 'large-capacity'],
    url: 'https://www.metlifestadium.com',
    status: 'active',
    eventsCount: 12,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-01-15'),
    updatedBy: 'admin@momentumww.com',
    updatedByName: 'System Admin',
    updatedOn: new Date('2025-11-10'),
  },
  {
    id: 'ven-002',
    name: 'Madison Square Garden',
    fullAddress: '4 Pennsylvania Plaza, New York, NY 10001, USA',
    formattedAddress: 'Madison Square Garden, New York, NY 10001',
    country: 'USA',
    city: 'New York',
    state: 'New York',
    stateCode: 'NY',
    postCode: '10001',
    address: '4 Pennsylvania Plaza',
    latitude: 40.7505,
    longitude: -73.9934,
    category: 'Arena',
    platform: 'Google Maps',
    poiScope: 'Sports & Entertainment',
    entityType: 'Multi-purpose Arena',
    subCategory: 'Indoor Arena',
    tags: ['sports', 'basketball', 'hockey', 'concerts'],
    url: 'https://www.msg.com',
    status: 'active',
    eventsCount: 28,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-01-15'),
  },
  {
    id: 'ven-003',
    name: 'Times Square',
    fullAddress: 'Times Square, Manhattan, NY 10036, USA',
    formattedAddress: 'Times Square, New York, NY 10036',
    country: 'USA',
    city: 'New York',
    state: 'New York',
    stateCode: 'NY',
    postCode: '10036',
    address: 'Broadway & 7th Avenue',
    latitude: 40.7580,
    longitude: -73.9855,
    category: 'Street',
    platform: 'Google Maps',
    poiScope: 'Public Space',
    entityType: 'Public Plaza',
    subCategory: 'Street Activation',
    tags: ['sampling', 'brand activation', 'high-traffic', 'tourism'],
    url: 'https://www.timessquarenyc.org',
    status: 'active',
    eventsCount: 45,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-01-20'),
  },
  // Convention centers
  {
    id: 'ven-004',
    name: 'Javits Center',
    fullAddress: '429 11th Ave, New York, NY 10001, USA',
    formattedAddress: 'Jacob K. Javits Convention Center, New York, NY',
    country: 'USA',
    city: 'New York',
    state: 'New York',
    stateCode: 'NY',
    postCode: '10001',
    address: '429 11th Ave',
    latitude: 40.7558,
    longitude: -74.0028,
    category: 'Convention Center',
    platform: 'Google Maps',
    poiScope: 'Events & Exhibitions',
    entityType: 'Convention Center',
    subCategory: 'Trade Show Venue',
    tags: ['trade show', 'exhibitions', 'conventions'],
    url: 'https://www.javitscenter.com',
    status: 'active',
    eventsCount: 8,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-02-01'),
  },
  // Parks
  {
    id: 'ven-005',
    name: 'Central Park',
    fullAddress: 'Central Park, New York, NY 10024, USA',
    formattedAddress: 'Central Park, New York, NY',
    country: 'USA',
    city: 'New York',
    state: 'New York',
    stateCode: 'NY',
    postCode: '10024',
    address: 'Central Park West',
    latitude: 40.7829,
    longitude: -73.9654,
    category: 'Park',
    platform: 'Google Maps',
    poiScope: 'Public Space',
    entityType: 'Public Park',
    subCategory: 'Outdoor Activation',
    tags: ['outdoor', 'recreation', 'festivals', 'brand activation'],
    url: 'https://www.centralparknyc.org',
    status: 'active',
    eventsCount: 15,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-02-05'),
  },
  // West Coast venues
  {
    id: 'ven-006',
    name: 'SoFi Stadium',
    fullAddress: '1001 S Stadium Dr, Inglewood, CA 90301, USA',
    formattedAddress: 'SoFi Stadium, Inglewood, CA 90301',
    country: 'USA',
    city: 'Inglewood',
    state: 'California',
    stateCode: 'CA',
    postCode: '90301',
    address: '1001 S Stadium Dr',
    latitude: 33.9535,
    longitude: -118.3390,
    category: 'Stadium',
    platform: 'Google Maps',
    poiScope: 'Sports & Entertainment',
    entityType: 'Sports Stadium',
    subCategory: 'NFL Stadium',
    tags: ['sports', 'football', 'concerts', 'super-bowl'],
    url: 'https://www.sofistadium.com',
    status: 'active',
    eventsCount: 9,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-03-01'),
  },
  {
    id: 'ven-007',
    name: 'Santa Monica Pier',
    fullAddress: '200 Santa Monica Pier, Santa Monica, CA 90401, USA',
    formattedAddress: 'Santa Monica Pier, Santa Monica, CA',
    country: 'USA',
    city: 'Santa Monica',
    state: 'California',
    stateCode: 'CA',
    postCode: '90401',
    address: '200 Santa Monica Pier',
    latitude: 34.0094,
    longitude: -118.4973,
    category: 'Street',
    platform: 'Google Maps',
    poiScope: 'Tourist Attraction',
    entityType: 'Public Pier',
    subCategory: 'Outdoor Activation',
    tags: ['beach', 'tourism', 'sampling', 'brand activation'],
    url: 'https://www.santamonicapier.org',
    status: 'active',
    eventsCount: 22,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-03-10'),
  },
  // Chicago venues
  {
    id: 'ven-008',
    name: 'Soldier Field',
    fullAddress: '1410 Special Olympics Dr, Chicago, IL 60605, USA',
    formattedAddress: 'Soldier Field, Chicago, IL 60605',
    country: 'USA',
    city: 'Chicago',
    state: 'Illinois',
    stateCode: 'IL',
    postCode: '60605',
    address: '1410 Special Olympics Dr',
    latitude: 41.8623,
    longitude: -87.6167,
    category: 'Stadium',
    platform: 'Google Maps',
    poiScope: 'Sports & Entertainment',
    entityType: 'Sports Stadium',
    subCategory: 'NFL Stadium',
    tags: ['sports', 'football', 'concerts'],
    url: 'https://www.soldierfield.com',
    status: 'active',
    eventsCount: 5,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-03-15'),
  },
  {
    id: 'ven-009',
    name: 'McCormick Place',
    fullAddress: '2301 S King Dr, Chicago, IL 60616, USA',
    formattedAddress: 'McCormick Place, Chicago, IL',
    country: 'USA',
    city: 'Chicago',
    state: 'Illinois',
    stateCode: 'IL',
    postCode: '60616',
    address: '2301 S King Dr',
    latitude: 41.8508,
    longitude: -87.6176,
    category: 'Convention Center',
    platform: 'Google Maps',
    poiScope: 'Events & Exhibitions',
    entityType: 'Convention Center',
    subCategory: 'Trade Show Venue',
    tags: ['trade show', 'conventions', 'exhibitions'],
    url: 'https://www.mccormickplace.com',
    status: 'active',
    eventsCount: 7,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-04-01'),
  },
  // Texas venues
  {
    id: 'ven-010',
    name: 'AT&T Stadium',
    fullAddress: '1 AT&T Way, Arlington, TX 76011, USA',
    formattedAddress: 'AT&T Stadium, Arlington, TX 76011',
    country: 'USA',
    city: 'Arlington',
    state: 'Texas',
    stateCode: 'TX',
    postCode: '76011',
    address: '1 AT&T Way',
    latitude: 32.7473,
    longitude: -97.0945,
    category: 'Stadium',
    platform: 'Google Maps',
    poiScope: 'Sports & Entertainment',
    entityType: 'Sports Stadium',
    subCategory: 'NFL Stadium',
    tags: ['sports', 'football', 'concerts', 'large-capacity'],
    url: 'https://attstadium.com',
    status: 'active',
    eventsCount: 6,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-04-10'),
  },
  // Miami venues
  {
    id: 'ven-011',
    name: 'Hard Rock Stadium',
    fullAddress: '347 Don Shula Dr, Miami Gardens, FL 33056, USA',
    formattedAddress: 'Hard Rock Stadium, Miami Gardens, FL',
    country: 'USA',
    city: 'Miami Gardens',
    state: 'Florida',
    stateCode: 'FL',
    postCode: '33056',
    address: '347 Don Shula Dr',
    latitude: 25.9580,
    longitude: -80.2389,
    category: 'Stadium',
    platform: 'Google Maps',
    poiScope: 'Sports & Entertainment',
    entityType: 'Sports Stadium',
    subCategory: 'NFL Stadium',
    tags: ['sports', 'football', 'concerts', 'super-bowl'],
    url: 'https://www.hardrockstadium.com',
    status: 'active',
    eventsCount: 4,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-05-01'),
  },
  {
    id: 'ven-012',
    name: 'South Beach',
    fullAddress: 'Ocean Drive, Miami Beach, FL 33139, USA',
    formattedAddress: 'South Beach, Miami Beach, FL',
    country: 'USA',
    city: 'Miami Beach',
    state: 'Florida',
    stateCode: 'FL',
    postCode: '33139',
    address: 'Ocean Drive',
    latitude: 25.7907,
    longitude: -80.1300,
    category: 'Street',
    platform: 'Google Maps',
    poiScope: 'Tourist Attraction',
    entityType: 'Beach Area',
    subCategory: 'Outdoor Activation',
    tags: ['beach', 'tourism', 'sampling', 'brand activation'],
    status: 'active',
    eventsCount: 18,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-05-10'),
  },
  // Boston venues
  {
    id: 'ven-013',
    name: 'Gillette Stadium',
    fullAddress: '1 Patriot Pl, Foxborough, MA 02035, USA',
    formattedAddress: 'Gillette Stadium, Foxborough, MA',
    country: 'USA',
    city: 'Foxborough',
    state: 'Massachusetts',
    stateCode: 'MA',
    postCode: '02035',
    address: '1 Patriot Pl',
    latitude: 42.0909,
    longitude: -71.2643,
    category: 'Stadium',
    platform: 'Google Maps',
    poiScope: 'Sports & Entertainment',
    entityType: 'Sports Stadium',
    subCategory: 'NFL Stadium',
    tags: ['sports', 'football', 'concerts'],
    url: 'https://www.gillettestadium.com',
    status: 'active',
    eventsCount: 3,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-06-01'),
  },
  // Las Vegas venues
  {
    id: 'ven-014',
    name: 'Allegiant Stadium',
    fullAddress: '3333 Al Davis Way, Las Vegas, NV 89118, USA',
    formattedAddress: 'Allegiant Stadium, Las Vegas, NV',
    country: 'USA',
    city: 'Las Vegas',
    state: 'Nevada',
    stateCode: 'NV',
    postCode: '89118',
    address: '3333 Al Davis Way',
    latitude: 36.0909,
    longitude: -115.1835,
    category: 'Stadium',
    platform: 'Google Maps',
    poiScope: 'Sports & Entertainment',
    entityType: 'Sports Stadium',
    subCategory: 'NFL Stadium',
    tags: ['sports', 'football', 'concerts', 'super-bowl'],
    url: 'https://www.allegiantstadium.com',
    status: 'active',
    eventsCount: 7,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-06-15'),
  },
  {
    id: 'ven-015',
    name: 'Las Vegas Strip',
    fullAddress: 'Las Vegas Blvd S, Las Vegas, NV 89109, USA',
    formattedAddress: 'Las Vegas Strip, Las Vegas, NV',
    country: 'USA',
    city: 'Las Vegas',
    state: 'Nevada',
    stateCode: 'NV',
    postCode: '89109',
    address: 'Las Vegas Blvd S',
    latitude: 36.1147,
    longitude: -115.1729,
    category: 'Street',
    platform: 'Google Maps',
    poiScope: 'Tourist Attraction',
    entityType: 'Entertainment District',
    subCategory: 'Street Activation',
    tags: ['tourism', 'brand activation', 'sampling', 'high-traffic'],
    status: 'active',
    eventsCount: 31,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-07-01'),
  },
  // Seattle venues
  {
    id: 'ven-016',
    name: 'Lumen Field',
    fullAddress: '800 Occidental Ave S, Seattle, WA 98134, USA',
    formattedAddress: 'Lumen Field, Seattle, WA',
    country: 'USA',
    city: 'Seattle',
    state: 'Washington',
    stateCode: 'WA',
    postCode: '98134',
    address: '800 Occidental Ave S',
    latitude: 47.5952,
    longitude: -122.3316,
    category: 'Stadium',
    platform: 'Google Maps',
    poiScope: 'Sports & Entertainment',
    entityType: 'Sports Stadium',
    subCategory: 'NFL Stadium',
    tags: ['sports', 'football', 'concerts'],
    url: 'https://www.lumenfield.com',
    status: 'active',
    eventsCount: 5,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-07-15'),
  },
  // Additional special venues
  {
    id: 'ven-017',
    name: 'Navy Pier Chicago',
    fullAddress: '600 E Grand Ave, Chicago, IL 60611, USA',
    formattedAddress: 'Navy Pier, Chicago, IL',
    country: 'USA',
    city: 'Chicago',
    state: 'Illinois',
    stateCode: 'IL',
    postCode: '60611',
    address: '600 E Grand Ave',
    latitude: 41.8919,
    longitude: -87.6051,
    category: 'Other',
    platform: 'Google Maps',
    poiScope: 'Tourist Attraction',
    entityType: 'Entertainment Complex',
    subCategory: 'Mixed Use Venue',
    tags: ['tourism', 'festivals', 'family', 'brand activation'],
    url: 'https://navypier.org',
    status: 'active',
    eventsCount: 12,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-08-01'),
  },
  {
    id: 'ven-018',
    name: 'Millennium Park',
    fullAddress: '201 E Randolph St, Chicago, IL 60602, USA',
    formattedAddress: 'Millennium Park, Chicago, IL',
    country: 'USA',
    city: 'Chicago',
    state: 'Illinois',
    stateCode: 'IL',
    postCode: '60602',
    address: '201 E Randolph St',
    latitude: 41.8826,
    longitude: -87.6226,
    category: 'Park',
    platform: 'Google Maps',
    poiScope: 'Public Space',
    entityType: 'Public Park',
    subCategory: 'Outdoor Activation',
    tags: ['outdoor', 'festivals', 'concerts', 'brand activation'],
    url: 'https://www.chicago.gov/millenniumpark',
    status: 'active',
    eventsCount: 10,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-08-10'),
  },
  // Archived venue example
  {
    id: 'ven-019',
    name: 'Oakland Coliseum',
    fullAddress: '7000 Coliseum Way, Oakland, CA 94621, USA',
    formattedAddress: 'Oakland Coliseum, Oakland, CA',
    country: 'USA',
    city: 'Oakland',
    state: 'California',
    stateCode: 'CA',
    postCode: '94621',
    address: '7000 Coliseum Way',
    latitude: 37.7516,
    longitude: -122.2005,
    category: 'Stadium',
    platform: 'Google Maps',
    poiScope: 'Sports & Entertainment',
    entityType: 'Sports Stadium',
    subCategory: 'Multi-sport Stadium',
    tags: ['sports', 'baseball', 'football'],
    url: 'https://www.oaklandcoliseum.com',
    status: 'archived',
    eventsCount: 2,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2024-01-01'),
    updatedBy: 'admin@momentumww.com',
    updatedByName: 'System Admin',
    updatedOn: new Date('2025-09-01'),
  },
  // Verified venue example
  {
    id: 'ven-020',
    name: 'Brooklyn Barclays Center',
    fullAddress: '620 Atlantic Ave, Brooklyn, NY 11217, USA',
    formattedAddress: 'Barclays Center, Brooklyn, NY',
    country: 'USA',
    city: 'Brooklyn',
    state: 'New York',
    stateCode: 'NY',
    postCode: '11217',
    address: '620 Atlantic Ave',
    latitude: 40.6826,
    longitude: -73.9754,
    category: 'Arena',
    platform: 'Google Maps',
    poiScope: 'Sports & Entertainment',
    entityType: 'Multi-purpose Arena',
    subCategory: 'Indoor Arena',
    tags: ['sports', 'basketball', 'hockey', 'concerts'],
    url: 'https://www.barclayscenter.com',
    status: 'verified',
    eventsCount: 16,
    createdBy: 'admin@momentumww.com',
    createdByName: 'System Admin',
    createdOn: new Date('2025-09-01'),
  },
];

// ============================================================================
// VENUE HELPER FUNCTIONS
// ============================================================================

/**
 * Get venues by city
 */
export function getVenuesByCity(city: string): Venue[] {
  return mockVenues.filter((v) => v.city.toLowerCase() === city.toLowerCase());
}

/**
 * Get venues by country
 */
export function getVenuesByCountry(country: string): Venue[] {
  return mockVenues.filter((v) => v.country.toLowerCase() === country.toLowerCase());
}

/**
 * Get venues by category
 */
export function getVenuesByCategory(category: Venue['category']): Venue[] {
  return mockVenues.filter((v) => v.category === category);
}

/**
 * Get venues by status
 */
export function getVenuesByStatus(status: Venue['status']): Venue[] {
  return mockVenues.filter((v) => v.status === status);
}

/**
 * Get active venues
 */
export function getActiveVenues(): Venue[] {
  return getVenuesByStatus('active');
}

/**
 * Get verified venues
 */
export function getVerifiedVenues(): Venue[] {
  return getVenuesByStatus('verified');
}

/**
 * Get archived venues
 */
export function getArchivedVenues(): Venue[] {
  return getVenuesByStatus('archived');
}

/**
 * Search venues by name or address
 */
export function searchVenues(query: string): Venue[] {
  const lowerQuery = query.toLowerCase();
  return mockVenues.filter(
    (v) =>
      v.name.toLowerCase().includes(lowerQuery) ||
      v.fullAddress.toLowerCase().includes(lowerQuery) ||
      v.city.toLowerCase().includes(lowerQuery) ||
      v.tags?.some((tag) => tag.toLowerCase().includes(lowerQuery))
  );
}

/**
 * Get most used venues (by events count)
 */
export function getMostUsedVenues(limit: number = 10): Venue[] {
  return [...mockVenues]
    .sort((a, b) => (b.eventsCount || 0) - (a.eventsCount || 0))
    .slice(0, limit);
}

/**
 * Get venues by state
 */
export function getVenuesByState(stateCode: string): Venue[] {
  return mockVenues.filter((v) => v.stateCode === stateCode);
}

// ============================================================================
// VENUE STATISTICS
// ============================================================================

export const mockVenueStatistics = {
  totalVenues: mockVenues.length,
  activeVenues: getActiveVenues().length,
  verifiedVenues: getVerifiedVenues().length,
  archivedVenues: getArchivedVenues().length,
  stadiums: getVenuesByCategory('Stadium').length,
  arenas: getVenuesByCategory('Arena').length,
  conventionCenters: getVenuesByCategory('Convention Center').length,
  parks: getVenuesByCategory('Park').length,
  streetActivations: getVenuesByCategory('Street').length,
  totalEvents: mockVenues.reduce((sum, v) => sum + (v.eventsCount || 0), 0),
  averageEventsPerVenue: mockVenues.reduce((sum, v) => sum + (v.eventsCount || 0), 0) / mockVenues.length,
  topVenue: getMostUsedVenues(1)[0],
};

// ============================================================================
// EMPLOYEE ONBOARDING SYSTEM - MOCK DATA
// ============================================================================

import type { PreHire, Hardware, Software, Package } from '../types';

/**
 * Mock Hardware Inventory
 * Sample hardware items for equipment provisioning
 */
export const mockHardware: Hardware[] = [
  {
    id: 'hw-001',
    type: 'computer',
    model: 'MacBook Pro 16" M3 Max',
    manufacturer: 'Apple',
    specifications: {
      processor: 'M3 Max',
      ram: '64GB',
      storage: '2TB SSD',
    },
    status: 'available',
    cost: 4299.00,
  },
  {
    id: 'hw-002',
    type: 'monitor',
    model: 'Dell UltraSharp 27" 4K',
    manufacturer: 'Dell',
    specifications: {
      screenSize: '27" 4K',
    },
    status: 'available',
    cost: 599.99,
  },
];

/**
 * Mock Software Catalog
 * Sample software and licenses
 */
export const mockSoftware: Software[] = [
  {
    id: 'sw-001',
    name: 'Adobe Creative Cloud',
    vendor: 'Adobe',
    licenseType: 'subscription',
    requiresApproval: false,
    cost: 54.99,
    renewalFrequency: 'monthly',
    description: 'Complete creative suite',
  },
  {
    id: 'sw-002',
    name: 'Cinema 4D Studio',
    vendor: 'Maxon',
    licenseType: 'subscription',
    requiresApproval: true,
    approver: 'Steve Sanderson',
    cost: 94.99,
    renewalFrequency: 'monthly',
    description: '3D modeling and animation',
  },
];

/**
 * Mock Equipment Packages
 * Pre-configured bundles for common roles
 */
export const mockPackages: Package[] = [
  {
    id: 'pkg-xd-std-001',
    name: 'XD Designer Standard',
    description: 'Standard equipment package for Experience Designers',
    roleTarget: ['XD Designer', 'Senior XD Designer'],
    departmentTarget: ['Creative', 'IPTC'],
    hardware: mockHardware,
    software: mockSoftware,
    licenses: mockSoftware,
    isStandard: true,
    createdBy: 'IT Admin',
    createdDate: new Date('2024-01-15'),
    lastModified: new Date('2024-01-15'),
  },
];

/**
 * Mock Pre-Hire Records
 * Sample candidate tracking data
 */
export const mockPreHires: PreHire[] = [
  {
    id: 'pre-2025-001',
    candidateName: 'Jane Smith',
    email: 'jane.smith@momentumww.com',
    role: 'XD Designer',
    department: 'Creative',
    startDate: new Date('2025-12-01'),
    hiringManager: 'John Doe',
    status: 'accepted',
    assignedPackage: mockPackages[0],
    createdBy: 'Camille (HR)',
    createdDate: new Date('2024-11-10'),
    lastModified: new Date('2024-11-10'),
  },
  {
    id: 'pre-2025-002',
    candidateName: 'Michael Chen',
    email: 'michael.chen@momentumww.com',
    role: 'Motion Designer',
    department: 'Creative',
    startDate: new Date('2025-11-25'),
    hiringManager: 'Sarah Johnson',
    status: 'offered',
    createdBy: 'Payton (HR)',
    createdDate: new Date('2024-11-12'),
    lastModified: new Date('2024-11-12'),
  },
  {
    id: 'pre-2025-003',
    candidateName: 'Emily Rodriguez',
    email: 'emily.rodriguez@momentumww.com',
    role: 'Project Manager',
    department: 'IPTC',
    startDate: new Date('2025-12-15'),
    hiringManager: 'Alex Thompson',
    status: 'candidate',
    createdBy: 'Camille (HR)',
    createdDate: new Date('2024-11-08'),
    lastModified: new Date('2024-11-08'),
  },
];

/**
 * Get pre-hires by status
 */
export function getPreHiresByStatus(status: PreHire['status']): PreHire[] {
  return mockPreHires.filter((p) => p.status === status);
}

/**
 * Get pre-hires by department
 */
export function getPreHiresByDepartment(department: string): PreHire[] {
  return mockPreHires.filter((p) => p.department === department);
}

/**
 * Get pre-hires starting in date range
 */
export function getPreHiresByDateRange(startDate: Date, endDate: Date): PreHire[] {
  return mockPreHires.filter((p) => p.startDate >= startDate && p.startDate <= endDate);
}

// ============================================================================
// ADDITIONAL ONBOARDING EXPORTS
// ============================================================================

/**
 * Mock Employees
 * Full employee records with onboarding status
 */
export const mockEmployees: Employee[] = [
  {
    id: 'emp-001',
    activeDirectoryId: 'ad-001',
    workdayId: 'wd-001',
    name: 'John Smith',
    email: 'john.smith@momentumww.com',
    department: 'Creative',
    role: 'Senior Designer',
    startDate: new Date('2023-06-15'),
    manager: 'Jane Doe',
    assignedPackage: mockPackages[0],
    actualHardware: mockHardware,
    actualSoftware: mockSoftware,
    onboardingStatus: 'active',
    onboardingPhases: {
      adCreated: new Date('2023-06-10'),
      vantageCreated: new Date('2023-06-10'),
      workdayCreated: new Date('2023-06-12'),
      equipmentOrdered: new Date('2023-06-13'),
      equipmentReceived: new Date('2023-06-14'),
      onboardingComplete: new Date('2023-06-15'),
    },
    isPreloaded: false,
    needsPasswordReset: false,
    createdBy: 'HR System',
    createdDate: new Date('2023-06-10'),
    lastModified: new Date('2023-06-15'),
  },
];

/**
 * Mock Freeze Periods
 * Workday freeze period configurations
 */
export const mockFreezePeriods: any[] = [];

/**
 * Mock Freeze Period Notifications
 * Password reset and termination notifications during freeze periods
 */
export const mockFreezePeriodNotifications: any[] = [];

/**
 * Mock Approval Requests
 * Equipment and software approval tracking
 */
export const mockApprovalRequests: any[] = [];

/**
 * Mock Helix Tickets
 * IT ticketing system integration
 */
export const mockHelixTickets: any[] = [];

/**
 * Mock License Pools
 * Software license pool management
 */
export const mockLicensePools: any[] = [];

/**
 * Calculate total cost of a package
 * Helper function for package cost calculations
 */
export function calculatePackageCost(pkg: Package): number {
  const hardwareCost = pkg.hardware.reduce((sum, hw) => sum + (hw.cost || 0), 0);
  const softwareCost = pkg.software.reduce((sum, sw) => sum + (sw.cost || 0), 0);
  const licenseCost = pkg.licenses.reduce((sum, lic) => sum + (lic.cost || 0), 0);
  return hardwareCost + softwareCost + licenseCost;
}
