// ============================================================================
// ESTIMATECRAFTER - DAX MEASURES
// ============================================================================
// Data Source: vw_EstimateCrafter
// Created: 2025-10-22
// Version: 1.0.0
// ============================================================================

// ============================================================================
// BASE METRICS
// ============================================================================

// Total Events
Total Events = COUNTROWS(vw_EstimateCrafter)

// Unique Users
Unique Users = DISTINCTCOUNT(vw_EstimateCrafter[UserEmail])

// Unique Sessions
Unique Sessions = DISTINCTCOUNT(vw_EstimateCrafter[SessionID])

// Events Per Session
Avg Events Per Session =
DIVIDE(
    [Total Events],
    [Unique Sessions],
    0
)

// ============================================================================
// ESTIMATE METRICS
// ============================================================================

// Estimates Generated
Estimates Generated =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "estimateGenerated"
)

// Average Estimate Value
Avg Estimate Value =
AVERAGE(vw_EstimateCrafter[GrandTotal])

// Total Estimate Value (Sum)
Total Estimate Value =
SUM(vw_EstimateCrafter[GrandTotal])

// Minimum Estimate
Min Estimate =
MIN(vw_EstimateCrafter[GrandTotal])

// Maximum Estimate
Max Estimate =
MAX(vw_EstimateCrafter[GrandTotal])

// Median Estimate Value
Median Estimate =
MEDIAN(vw_EstimateCrafter[GrandTotal])

// Average Item Count Per Estimate
Avg Items Per Estimate =
CALCULATE(
    AVERAGE(vw_EstimateCrafter[ItemCount]),
    vw_EstimateCrafter[EventType] = "estimateGenerated"
)

// Average Generation Time (Seconds)
Avg Generation Time =
CALCULATE(
    AVERAGE(vw_EstimateCrafter[DurationSeconds]),
    vw_EstimateCrafter[EventType] = "estimateGenerated"
)

// ============================================================================
// PROJECT LIFECYCLE METRICS
// ============================================================================

// Projects Created
Projects Created =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "projectCreated"
)

// Projects Imported
Projects Imported =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "projectImported"
)

// Projects Cleared
Projects Cleared =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "projectCleared"
)

// Unique Projects
Unique Projects =
DISTINCTCOUNT(vw_EstimateCrafter[ProjectName])

// Most Active Project
Most Active Project =
VAR ProjectEvents =
    FILTER(
        vw_EstimateCrafter,
        NOT ISBLANK(vw_EstimateCrafter[ProjectName])
    )
VAR MostActive =
    TOPN(
        1,
        SUMMARIZE(
            ProjectEvents,
            vw_EstimateCrafter[ProjectName]
        ),
        CALCULATE([Total Events]),
        DESC
    )
RETURN
    MAXX(MostActive, vw_EstimateCrafter[ProjectName])

// ============================================================================
// SCOPE CURATION METRICS
// ============================================================================

// Elements Modified
Elements Modified =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "elementModified"
)

// Elements Added
Elements Added =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "elementAdded"
)

// Elements Removed
Elements Removed =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "elementRemoved"
)

// Zones Created
Zones Created =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "zoneCreated"
)

// Total Scope Changes
Total Scope Changes =
[Elements Modified] + [Elements Added] + [Elements Removed] + [Zones Created]

// ============================================================================
// VALUE ENGINEERING (VE) METRICS
// ============================================================================

// VE Options Applied
VE Options Applied =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "veOptionApplied"
)

// VE Options Dismissed
VE Options Dismissed =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "veOptionDismissed"
)

// VE Acceptance Rate
VE Acceptance Rate =
DIVIDE(
    [VE Options Applied],
    [VE Options Applied] + [VE Options Dismissed],
    0
)

// Estimated VE Savings (Parse from VESavings string)
Total VE Savings =
VAR VESavings =
    FILTER(
        vw_EstimateCrafter,
        vw_EstimateCrafter[EventType] = "veOptionApplied"
            && NOT ISBLANK(vw_EstimateCrafter[VESavings])
    )
VAR ParsedSavings =
    ADDCOLUMNS(
        VESavings,
        "MinSavings",
        VALUE(
            SUBSTITUTE(
                LEFT(
                    vw_EstimateCrafter[VESavings],
                    FIND(",", vw_EstimateCrafter[VESavings], 1, 1) - 2
                ),
                "$",
                ""
            )
        )
    )
RETURN
    SUMX(ParsedSavings, [MinSavings])

// Average VE Savings Per Option
Avg VE Savings =
DIVIDE(
    [Total VE Savings],
    [VE Options Applied],
    0
)

// ============================================================================
// MISSING ITEMS METRICS
// ============================================================================

// Missing Items Added
Missing Items Added =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "missingItemAdded"
)

// Missing Items Dismissed
Missing Items Dismissed =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "missingItemDismissed"
)

// Missing Item Acceptance Rate
Missing Item Acceptance Rate =
DIVIDE(
    [Missing Items Added],
    [Missing Items Added] + [Missing Items Dismissed],
    0
)

// Total Value of Missing Items Added
Missing Items Total Value =
CALCULATE(
    SUM(vw_EstimateCrafter[UnitCost]),
    vw_EstimateCrafter[EventType] = "missingItemAdded"
)

// Average Missing Item Value
Avg Missing Item Value =
CALCULATE(
    AVERAGE(vw_EstimateCrafter[UnitCost]),
    vw_EstimateCrafter[EventType] = "missingItemAdded"
)

// ============================================================================
// AI CHAT METRICS
// ============================================================================

// Chat Messages Sent
Chat Messages =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "chatMessageSent"
)

// Average Message Length
Avg Message Length =
CALCULATE(
    AVERAGE(vw_EstimateCrafter[MessageLength]),
    vw_EstimateCrafter[EventType] = "chatMessageSent"
)

// Average Conversation Length
Avg Conversation Length =
CALCULATE(
    AVERAGE(vw_EstimateCrafter[HistoryLength]),
    vw_EstimateCrafter[EventType] = "chatMessageSent"
)

// Chat Adoption Rate (% of sessions with chat)
Chat Adoption Rate =
VAR SessionsWithChat =
    CALCULATE(
        DISTINCTCOUNT(vw_EstimateCrafter[SessionID]),
        vw_EstimateCrafter[EventType] = "chatMessageSent"
    )
RETURN
    DIVIDE(SessionsWithChat, [Unique Sessions], 0)

// ============================================================================
// SCENARIO METRICS
// ============================================================================

// Scenarios Created
Scenarios Created =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "scenarioCreated"
)

// Unique Scenario Names
Unique Scenarios =
DISTINCTCOUNT(vw_EstimateCrafter[NewScenario])

// Average Scenarios Per Project
Avg Scenarios Per Project =
VAR ProjectsWithScenarios =
    CALCULATE(
        DISTINCTCOUNT(vw_EstimateCrafter[SessionID]),
        vw_EstimateCrafter[EventType] = "scenarioCreated"
    )
RETURN
    DIVIDE([Scenarios Created], ProjectsWithScenarios, 0)

// Most Common Base Scenario
Most Common Base Scenario =
VAR ScenarioEvents =
    FILTER(
        vw_EstimateCrafter,
        NOT ISBLANK(vw_EstimateCrafter[BaseScenario])
    )
VAR MostCommon =
    TOPN(
        1,
        SUMMARIZE(
            ScenarioEvents,
            vw_EstimateCrafter[BaseScenario]
        ),
        CALCULATE([Total Events]),
        DESC
    )
RETURN
    MAXX(MostCommon, vw_EstimateCrafter[BaseScenario])

// ============================================================================
// INSIGHTS METRICS
// ============================================================================

// Insights Viewed
Insights Viewed =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "insightViewed"
)

// Unique Insight Types Viewed
Unique Insight Types =
DISTINCTCOUNT(vw_EstimateCrafter[InsightType])

// Most Viewed Insight Type
Most Viewed Insight =
VAR InsightEvents =
    FILTER(
        vw_EstimateCrafter,
        NOT ISBLANK(vw_EstimateCrafter[InsightType])
    )
VAR MostViewed =
    TOPN(
        1,
        SUMMARIZE(
            InsightEvents,
            vw_EstimateCrafter[InsightType]
        ),
        CALCULATE([Total Events]),
        DESC
    )
RETURN
    MAXX(MostViewed, vw_EstimateCrafter[InsightType])

// ============================================================================
// EXPORT METRICS
// ============================================================================

// Total Exports
Total Exports =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "dataExported"
)

// PDF Exports
PDF Exports =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "dataExported",
    vw_EstimateCrafter[ExportFormat] = "pdf"
)

// CSV Exports
CSV Exports =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "dataExported",
    vw_EstimateCrafter[ExportFormat] = "csv"
)

// HTML Exports (SOW)
HTML Exports =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "dataExported",
    vw_EstimateCrafter[ExportFormat] = "html"
)

// MomoXD Exports (Project Files)
MomoXD Exports =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "dataExported",
    vw_EstimateCrafter[ExportFormat] = "momoXD"
)

// Export Rate (% of estimates that get exported)
Export Rate =
DIVIDE(
    [Total Exports],
    [Estimates Generated],
    0
)

// Most Popular Export Format
Most Popular Export Format =
VAR ExportEvents =
    FILTER(
        vw_EstimateCrafter,
        vw_EstimateCrafter[EventType] = "dataExported"
    )
VAR MostPopular =
    TOPN(
        1,
        SUMMARIZE(
            ExportEvents,
            vw_EstimateCrafter[ExportFormat]
        ),
        CALCULATE([Total Events]),
        DESC
    )
RETURN
    MAXX(MostPopular, vw_EstimateCrafter[ExportFormat])

// SOW Generation Rate
SOW Generation Rate =
VAR SOWExports =
    CALCULATE(
        [Total Events],
        vw_EstimateCrafter[EventType] = "dataExported",
        vw_EstimateCrafter[ExportType] = "sow"
    )
RETURN
    DIVIDE(SOWExports, [Estimates Generated], 0)

// ============================================================================
// BATCH OPERATIONS
// ============================================================================

// Batch Reprice Triggered
Batch Reprices =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventType] = "batchRepriceTriggered"
)

// Average Items Repriced
Avg Items Repriced =
CALCULATE(
    AVERAGE(vw_EstimateCrafter[ItemCount]),
    vw_EstimateCrafter[EventType] = "batchRepriceTriggered"
)

// ============================================================================
// USER ENGAGEMENT METRICS
// ============================================================================

// Active Users Today
Active Users Today =
CALCULATE(
    [Unique Users],
    vw_EstimateCrafter[EventDate] = TODAY()
)

// Active Users This Week
Active Users This Week =
VAR StartOfWeek = TODAY() - WEEKDAY(TODAY(), 2) + 1
RETURN
    CALCULATE(
        [Unique Users],
        vw_EstimateCrafter[EventDate] >= StartOfWeek
    )

// Active Users This Month
Active Users This Month =
CALCULATE(
    [Unique Users],
    MONTH(vw_EstimateCrafter[EventDate]) = MONTH(TODAY()),
    YEAR(vw_EstimateCrafter[EventDate]) = YEAR(TODAY())
)

// Power Users (5+ Sessions)
Power Users =
VAR UserSessions =
    SUMMARIZE(
        vw_EstimateCrafter,
        vw_EstimateCrafter[UserEmail],
        "SessionCount", CALCULATE([Unique Sessions])
    )
VAR PowerUserList =
    FILTER(
        UserSessions,
        [SessionCount] >= 5
    )
RETURN
    COUNTROWS(PowerUserList)

// Average Session Duration (Minutes)
Avg Session Duration Min =
VAR SessionDurations =
    ADDCOLUMNS(
        VALUES(vw_EstimateCrafter[SessionID]),
        "Duration",
        DATEDIFF(
            CALCULATE(MIN(vw_EstimateCrafter[EventTimestamp])),
            CALCULATE(MAX(vw_EstimateCrafter[EventTimestamp])),
            MINUTE
        )
    )
RETURN
    AVERAGEX(SessionDurations, [Duration])

// ============================================================================
// AI ADOPTION METRICS
// ============================================================================

// AI Feature Usage (VE + Missing Items + Chat)
AI Feature Usage =
[VE Options Applied] + [Missing Items Added] + [Chat Messages]

// AI Adoption Rate (% of sessions using AI)
AI Adoption Rate =
VAR SessionsWithAI =
    CALCULATE(
        DISTINCTCOUNT(vw_EstimateCrafter[SessionID]),
        vw_EstimateCrafter[EventType] IN {
            "veOptionApplied",
            "missingItemAdded",
            "chatMessageSent"
        }
    )
RETURN
    DIVIDE(SessionsWithAI, [Unique Sessions], 0)

// ============================================================================
// FUNNEL METRICS
// ============================================================================

// Funnel: Project to Estimate
Project to Estimate Rate =
VAR Projects = [Projects Created] + [Projects Imported]
RETURN
    DIVIDE([Estimates Generated], Projects, 0)

// Funnel: Estimate to Scenario
Estimate to Scenario Rate =
DIVIDE(
    [Scenarios Created],
    [Estimates Generated],
    0
)

// Funnel: Estimate to Export
Estimate to Export Rate =
DIVIDE(
    [Total Exports],
    [Estimates Generated],
    0
)

// Funnel: Estimate to VE
Estimate to VE Rate =
VAR SessionsWithEstimates =
    CALCULATE(
        DISTINCTCOUNT(vw_EstimateCrafter[SessionID]),
        vw_EstimateCrafter[EventType] = "estimateGenerated"
    )
VAR SessionsWithVE =
    CALCULATE(
        DISTINCTCOUNT(vw_EstimateCrafter[SessionID]),
        vw_EstimateCrafter[EventType] = "veOptionApplied"
    )
RETURN
    DIVIDE(SessionsWithVE, SessionsWithEstimates, 0)

// ============================================================================
// TIME-BASED METRICS
// ============================================================================

// Events Yesterday
Events Yesterday =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventDate] = TODAY() - 1
)

// Events Last 7 Days
Events Last 7 Days =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventDate] >= TODAY() - 7
)

// Events Last 30 Days
Events Last 30 Days =
CALCULATE(
    [Total Events],
    vw_EstimateCrafter[EventDate] >= TODAY() - 30
)

// Growth Rate (Month over Month)
MoM Growth Rate =
VAR CurrentMonth = [Total Events]
VAR LastMonth =
    CALCULATE(
        [Total Events],
        DATEADD(vw_EstimateCrafter[EventDate], -1, MONTH)
    )
RETURN
    DIVIDE(CurrentMonth - LastMonth, LastMonth, 0)

// ============================================================================
// VALUE METRICS (Business Impact)
// ============================================================================

// Total Project Value Estimated
Total Project Value =
CALCULATE(
    SUM(vw_EstimateCrafter[GrandTotal]),
    vw_EstimateCrafter[EventType] = "estimateGenerated"
)

// Potential Savings from VE
Potential VE Savings =
[Total VE Savings]

// ROI from Missing Items
Missing Items ROI =
DIVIDE(
    [Missing Items Total Value],
    [Estimates Generated],
    0
)

// Average Value Per User
Avg Value Per User =
DIVIDE(
    [Total Project Value],
    [Unique Users],
    0
)

// ============================================================================
// CONDITIONAL FORMATTING HELPERS
// ============================================================================

// Trend Indicator
Trend Indicator =
VAR CurrentValue = [Total Events]
VAR PreviousValue =
    CALCULATE(
        [Total Events],
        DATEADD(vw_EstimateCrafter[EventDate], -1, MONTH)
    )
RETURN
    SWITCH(
        TRUE(),
        CurrentValue > PreviousValue, "▲ Increasing",
        CurrentValue < PreviousValue, "▼ Decreasing",
        CurrentValue = PreviousValue, "► Stable",
        "No Data"
    )

// ============================================================================
// END OF MEASURES
// ============================================================================
// Total Measures: 75
// To import: Copy each measure into Power BI Desktop (Modeling → New Measure)
// Or use Tabular Editor for bulk import
// ============================================================================
